-- MyInvoice.cz — purchase invoices data model
-- Issue #1: Add foundation for received/purchase invoices (přijaté faktury)
-- For DPH reporting: input VAT (vstupní DPH) + control statement (kontrolní hlášení) row B.1
--
-- Key design decisions (aligned with PURCHASE-INVOICE-ANALYSIS.md):
--   • Mirrors existing `invoices` + `invoice_items` pattern (snake_case, DECIMAL(12,2), JSON snapshots)
--   • Status: draft → received → booked → paid (or cancelled) — no sent/reminder flow
--   • supplier_id → the supplier we received from; stored in clients table (reused, not new table)
--   • invoice_number = supplier's own invoice number (unique per supplier per period)
--   • tax_date (DUZP) is critical for DPH period assignment
--   • Separate counter: format PF-YYYYMM-NNNN ("Přijatá faktura")
--   • Reverse charge supported: input VAT = 0, self-assessed by recipient

SET NAMES utf8mb4;
SET sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';

-- ==========================================================================
-- purchase_invoices
-- Comparable to `invoices` but for received documents from suppliers.
-- Fields mirror issued invoice structure with necessary adaptations.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS purchase_invoices (
    id                      BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,

    -- Internal varsymbol (company's own reference, separate from supplier invoice number)
    -- Format: PF-YYYYMM-NNNN generated by purchase_invoice_counters
    varsymbol               VARCHAR(20) NULL,

    -- Supplier (the party who issued us this invoice) — stored in clients table
    -- For purchase invoices the client record represents our supplier/counterparty
    supplier_id             BIGINT UNSIGNED NOT NULL,

    -- The supplier's own invoice number (unique per supplier + period for dedup)
    invoice_number         VARCHAR(50) NOT NULL,

    -- Dates
    --   issue_date   = date on the supplier's invoice
    --   tax_date     = DUZP (date of taxable supply) — critical for DPH period
    --   due_date     = payment deadline per supplier's terms
    --   received_at  = when we physically received / logged the invoice
    issue_date             DATE NOT NULL,
    tax_date               DATE NULL,                        -- DUZP (date of taxable supply)
    due_date               DATE NOT NULL,
    received_at            DATE NOT NULL,                    -- when we got the invoice in our system

    -- Currency (ISO 4217) — most will be CZK but EUR and others supported
    currency_id            INT UNSIGNED NOT NULL,

    -- Reverse charge: 1 = recipient self-assesses VAT (B2B foreign), 0 = standard
    reverse_charge        TINYINT(1) NOT NULL DEFAULT 0,

    -- Language for invoice text / PDF
    language               ENUM('cs','en') NOT NULL DEFAULT 'cs',

    -- Notes (internal company memos)
    note_above_items       TEXT NULL,
    note_below_items      TEXT NULL,

    -- Supplier snapshot (immutable record of supplier data at time of receipt)
    -- Similar to client_snapshot on issued invoices
    supplier_snapshot      JSON NOT NULL,

    -- Our own company data snapshot (for records / PDF)
    own_snapshot           JSON NULL,

    -- Denormalized totals (recalculated on every item change)
    total_without_vat      DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_vat              DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_with_vat         DECIMAL(12,2) NOT NULL DEFAULT 0,
    rounding               DECIMAL(6,2) NOT NULL DEFAULT 0,

    -- Payment tracking
    advance_paid_amount    DECIMAL(12,2) NOT NULL DEFAULT 0,
    -- Generated column: amount still owed
    amount_to_pay          DECIMAL(12,2) AS (total_with_vat - advance_paid_amount) STORED,

    -- Status lifecycle: draft → received → booked → paid (cancelled at any point)
    --   draft     = being entered, not yet confirmed
    --   received  = confirmed as received (invoice logged)
    --   booked    = booked into accounting (posted)
    --   paid      = payment sent / matched
    --   cancelled = cancelled / voided
    status                 ENUM('draft','received','booked','paid','cancelled')
                              NOT NULL DEFAULT 'draft',

    -- Timestamps for key lifecycle events
    booked_at              TIMESTAMP NULL,                    -- booked into accounting
    paid_at                DATE NULL,                         -- actual payment date
    cancelled_at           TIMESTAMP NULL,

    -- PDF attachment (scanned or系统-generated record)
    pdf_path               VARCHAR(255) NULL,
    pdf_generated_at       TIMESTAMP NULL,

    -- Metadata
    created_by             BIGINT UNSIGNED NOT NULL,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    -- Constraints / indexes
    -- Unique varsymbol per supplier (idempotent auto-numbering guard)
    UNIQUE KEY uq_pi_supplier_varsymbol (supplier_id, varsymbol),
    -- Unique invoice number per supplier per year-month (prevents duplicate imports)
    UNIQUE KEY uq_pi_supplier_invoice_month (supplier_id, invoice_number, issue_date),

    KEY idx_pi_supplier    (supplier_id, issue_date DESC),
    KEY idx_pi_status      (status, due_date),
    KEY idx_pi_tax_date    (tax_date),
    KEY idx_pi_received    (received_at),

    CONSTRAINT fk_pi_supplier FOREIGN KEY (supplier_id) REFERENCES clients(id),
    CONSTRAINT fk_pi_currency FOREIGN KEY (currency_id) REFERENCES currencies(id),
    CONSTRAINT fk_pi_user     FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================================================
-- purchase_invoice_items
-- Parallel to `invoice_items`. Each row = one line item on a received invoice.
-- ==========================================================================

CREATE TABLE IF NOT EXISTS purchase_invoice_items (
    id                          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    purchase_invoice_id         BIGINT UNSIGNED NOT NULL,

    description                 TEXT NOT NULL,
    quantity                    DECIMAL(10,3) NOT NULL DEFAULT 1.000,
    unit                        VARCHAR(20) NOT NULL DEFAULT 'ks',
    unit_price_without_vat      DECIMAL(12,2) NOT NULL,

    -- VAT: references vat_rates (CZ-21, CZ-12, CZ-0, CZ-RC)
    -- Snapshot stored to preserve rate even if vat_rates table changes later
    vat_rate_id                 INT UNSIGNED NOT NULL,
    vat_rate_snapshot           DECIMAL(5,2) NOT NULL,          -- e.g. 21.00

    -- Denormalized line totals
    total_without_vat           DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_vat                   DECIMAL(12,2) NOT NULL DEFAULT 0,
    total_with_vat              DECIMAL(12,2) NOT NULL DEFAULT 0,

    order_index                 INT NOT NULL DEFAULT 0,       -- display order

    KEY idx_pii_invoice (purchase_invoice_id, order_index),
    CONSTRAINT fk_pii_invoice FOREIGN KEY (purchase_invoice_id)
        REFERENCES purchase_invoices(id) ON DELETE CASCADE,
    CONSTRAINT fk_pii_vat FOREIGN KEY (vat_rate_id) REFERENCES vat_rates(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ==========================================================================
-- purchase_invoice_counters
-- Auto-increment counter for varsymbol generation (format: PF-YYYYMM-NNNN)
-- Separate from issued invoice counters (invoice_counters table)
-- ==========================================================================

CREATE TABLE IF NOT EXISTS purchase_invoice_counters (
    client_id       BIGINT UNSIGNED NOT NULL,            -- references clients(id), same as purchase_invoices.supplier_id
    period_ym      CHAR(6) NOT NULL,                  -- "YYYYMM", e.g. "202605"
    last_number     INT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (client_id, period_ym),
    CONSTRAINT fk_pic_client FOREIGN KEY (client_id) REFERENCES clients(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
