// Číselník CZ-NACE / OKÉČ — zdroj: adisspr.mfcr.cz/dpr/epo_ciselnik?C=okec
// Aktualizováno: 2026-05-19
export interface NaceEntry { code: string; name: string }

export const NACE_CODES: NaceEntry[] = [
  { code: '10000', name: "ROSTLINNÁ A ŽIVOČIŠNÁ VÝROBA, MYSLIVOST A SOUVISEJÍCÍ ČINNOSTI" },
  { code: '100000', name: "VÝROBA POTRAVINÁŘSKÝCH VÝROBKŮ" },
  { code: '101000', name: "ZPRACOVÁNÍ A KONZERVOVÁNÍ MASA A VÝROBA MASNÝCH VÝROBKŮ" },
  { code: '101100', name: "ZPRACOVÁNÍ A KONZERVOVÁNÍ MASA, KROMĚ DRŮBEŽÍHO MASA" },
  { code: '101200', name: "ZPRACOVÁNÍ A KONZERVOVÁNÍ DRŮBEŽÍHO MASA" },
  { code: '101300', name: "VÝROBA MASNÝCH VÝROBKŮ A VÝROBKŮ Z DRŮBEŽÍHO MASA" },
  { code: '102000', name: "ZPRACOVÁNÍ A KONZERVOVÁNÍ RYB, KORÝŠŮ A MĚKKÝŠŮ" },
  { code: '103000', name: "ZPRACOVÁNÍ A KONZERVOVÁNÍ OVOCE A ZELENINY" },
  { code: '103100', name: "ZPRACOVÁNÍ A KONZERVOVÁNÍ BRAMBOR" },
  { code: '103200', name: "VÝROBA OVOCNÝCH A ZELENINOVÝCH ŠŤÁV" },
  { code: '103900', name: "OSTATNÍ ZPRACOVÁNÍ A KONZERVOVÁNÍ OVOCE A ZELENINY" },
  { code: '104000', name: "VÝROBA ROSTLINNÝCH A ŽIVOČIŠNÝCH OLEJŮ A TUKŮ" },
  { code: '104100', name: "VÝROBA OLEJŮ A TUKŮ" },
  { code: '104200', name: "VÝROBA MARGARÍNU A PODOBNÝCH JEDLÝCH TUKŮ" },
  { code: '105000', name: "VÝROBA MLÉČNÝCH VÝROBKŮ, VÝROBA ZMRZLINY A LEDU K LIDSKÉ SPOTŘEBĚ" },
  { code: '105100', name: "VÝROBA MLÉČNÝCH VÝROBKŮ" },
  { code: '105200', name: "VÝROBA ZMRZLINY A LEDU K LIDSKÉ SPOTŘEBĚ" },
  { code: '106000', name: "VÝROBA MLÝNSKÝCH A ŠKROBÁRENSKÝCH VÝROBKŮ" },
  { code: '106100', name: "VÝROBA MLÝNSKÝCH VÝROBKŮ" },
  { code: '106200', name: "VÝROBA ŠKROBÁRENSKÝCH VÝROBKŮ" },
  { code: '107000', name: "VÝROBA PEKAŘSKÝCH, CUKRÁŘSKÝCH A JINÝCH MOUČNÝCH VÝROBKŮ" },
  { code: '107100', name: "VÝROBA PEKAŘSKÝCH A CUKRÁŘSKÝCH VÝROBKŮ, KROMĚ TRVANLIVÝCH" },
  { code: '107200', name: "VÝROBA SUCHARŮ, SUŠENEK A TRVANLIVÝCH PEKAŘSKÝCH A CUKRÁŘSKÝCH VÝROBKŮ" },
  { code: '107300', name: "VÝROBA MOUČNÝCH VÝROBKŮ" },
  { code: '108000', name: "VÝROBA OSTATNÍCH POTRAVINÁŘSKÝCH VÝROBKŮ" },
  { code: '108100', name: "VÝROBA CUKRU" },
  { code: '108200', name: "VÝROBA KAKAA, ČOKOLÁDY A CUKROVINEK" },
  { code: '108300', name: "ZPRACOVÁNÍ ČAJE A KÁVY" },
  { code: '108400', name: "VÝROBA KOŘENÍ A PŘÍSAD PRO OCHUCENÍ" },
  { code: '108500', name: "VÝROBA HOTOVÝCH POKRMŮ" },
  { code: '108600', name: "VÝROBA HOMOGENIZOVANÝCH POTRAVINÁŘSKÝCH PŘÍPRAVKŮ A DIETETICKÝCH POTRAVIN" },
  { code: '108900', name: "VÝROBA OSTATNÍCH POTRAVINÁŘSKÝCH VÝROBKŮ J. N." },
  { code: '109000', name: "VÝROBA KRMIV" },
  { code: '109100', name: "VÝROBA KRMIV PRO HOSPODÁŘSKÁ ZVÍŘATA" },
  { code: '109200', name: "VÝROBA KRMIV PRO ZVÍŘATA V ZÁJMOVÉM CHOVU" },
  { code: '11000', name: "PĚSTOVÁNÍ PLODIN JINÝCH NEŽ TRVALÝCH" },
  { code: '110000', name: "VÝROBA NÁPOJŮ" },
  { code: '110100', name: "DESTILACE, REKTIFIKACE A MÍCHANÍ LIHOVIN" },
  { code: '110200', name: "VÝROBA VÍNA Z VINNÝCH HROZNŮ" },
  { code: '110300', name: "VÝROBA CIDERŮ A JINÝCH KVAŠENÝCH OVOCNÝCH NÁPOJŮ" },
  { code: '110400', name: "VÝROBA OSTATNÍCH NEDESTILOVANÝCH KVAŠENÝCH NÁPOJŮ" },
  { code: '110500', name: "VÝROBA PIVA" },
  { code: '110600', name: "VÝROBA SLADU" },
  { code: '110700', name: "VÝROBA NEALKOHOLICKÝCH NÁPOJŮ A BALENÝCH VOD" },
  { code: '11100', name: "PĚSTOVÁNÍ OBILOVIN JINÝCH NEŽ RÝŽE, LUŠTĚNIN A OLEJNATÝCH SEMEN" },
  { code: '11200', name: "PĚSTOVÁNÍ RÝŽE" },
  { code: '11300', name: "PĚSTOVÁNÍ ZELENINY A MELOUNŮ, KOŘENŮ A HLÍZ" },
  { code: '11400', name: "PĚSTOVÁNÍ CUKROVÉ TŘTINY" },
  { code: '11500', name: "PĚSTOVÁNÍ TABÁKU" },
  { code: '11600', name: "PĚSTOVÁNÍ PŘADNÝCH ROSTLIN" },
  { code: '11900', name: "PĚSTOVÁNÍ OSTATNÍCH PLODIN JINÝCH NEŽ TRVALÝCH" },
  { code: '12000', name: "PĚSTOVÁNÍ TRVALÝCH PLODIN" },
  { code: '120000', name: "VÝROBA TABÁKOVÝCH VÝROBKŮ" },
  { code: '12100', name: "PĚSTOVÁNÍ VINNÝCH HROZNŮ" },
  { code: '12200', name: "PĚSTOVÁNÍ TROPICKÉHO A SUBTROPICKÉHO OVOCE" },
  { code: '12300', name: "PĚSTOVÁNÍ CITRUSOVÝCH PLODŮ" },
  { code: '12400', name: "PĚSTOVÁNÍ JÁDROVÉHO A PECKOVÉHO OVOCE" },
  { code: '12500', name: "PĚSTOVÁNÍ OSTATNÍHO STROMOVÉHO A KEŘOVÉHO OVOCE A OŘECHŮ" },
  { code: '12600', name: "PĚSTOVÁNÍ OLEJNATÝCH PLODŮ" },
  { code: '12700', name: "PĚSTOVÁNÍ ROSTLIN PRO VÝROBU NÁPOJŮ" },
  { code: '12800', name: "PĚSTOVÁNÍ KOŘENÍ A AROMATICKÝCH, LÉČIVÝCH A FARMACEUTICKÝCH ROSTLIN" },
  { code: '12900', name: "PĚSTOVÁNÍ OSTATNÍCH TRVALÝCH PLODIN" },
  { code: '13000', name: "MNOŽENÍ ROSTLIN" },
  { code: '130000', name: "VÝROBA TEXTILIÍ" },
  { code: '131000', name: "ÚPRAVA A SPŘÁDÁNÍ TEXTILNÍCH VLÁKEN A PŘÍZE" },
  { code: '132000', name: "TKANÍ TEXTILIÍ" },
  { code: '133000', name: "KONEČNÁ ÚPRAVA TEXTILIÍ" },
  { code: '139000', name: "VÝROBA OSTATNÍCH TEXTILIÍ" },
  { code: '139100', name: "VÝROBA PLETENÝCH A HÁČKOVANÝCH TEXTILIÍ" },
  { code: '139200', name: "VÝROBA BYTOVÉHO TEXTILU A KONFEKČNÍCH BYTOVÝCH TEXTILIÍ" },
  { code: '139300', name: "VÝROBA KOBERCŮ A KOBERCOVÝCH PŘEDLOŽEK" },
  { code: '139400', name: "VÝROBA LAN, PROVAZŮ A SÍŤOVANÝCH VÝROBKŮ" },
  { code: '139500', name: "VÝROBA NETKANÝCH TEXTILIÍ A VÝROBKŮ Z NICH" },
  { code: '139600', name: "VÝROBA OSTATNÍCH TECHNICKÝCH A PRŮMYSLOVÝCH TEXTILIÍ" },
  { code: '139900', name: "VÝROBA OSTATNÍCH TEXTILIÍ J. N." },
  { code: '14000', name: "ŽIVOČIŠNÁ VÝROBA" },
  { code: '140000', name: "VÝROBA ODĚVŮ" },
  { code: '14100', name: "CHOV MLÉČNÉHO SKOTU" },
  { code: '141000', name: "VÝROBA PLETENÝCH A HÁČKOVANÝCH ODĚVŮ" },
  { code: '141010', name: "VÝROBA PLETENÝCH A HÁČKOVANÝCH PUNČOCHOVÝCH VÝROBKŮ" },
  { code: '141090', name: "VÝROBA OSTATNÍCH PLETENÝCH A HÁČKOVANÝCH ODĚVŮ" },
  { code: '14200', name: "CHOV OSTATNÍHO SKOTU A BUVOLŮ" },
  { code: '142000', name: "VÝROBA OSTATNÍCH ODĚVŮ A ODĚVNÍCH DOPLŇKŮ" },
  { code: '14300', name: "CHOV KONÍ A OSTATNÍCH KOŇOVITÝCH" },
  { code: '14400', name: "CHOV VELBLOUDŮ A VELBLOUDOVITÝCH" },
  { code: '14500', name: "CHOV OVCÍ A KOZ" },
  { code: '14600', name: "CHOV PRASAT" },
  { code: '14700', name: "CHOV DRŮBEŽE" },
  { code: '14800', name: "CHOV OSTATNÍCH ZVÍŘAT" },
  { code: '15000', name: "SMÍŠENÉ HOSPODAŘENÍ" },
  { code: '16000', name: "PODPŮRNÉ ČINNOSTI PRO ZEMĚDĚLSTVÍ A POSKLIZŇOVÉ ČINNOSTI" },
  { code: '16100', name: "PODPŮRNÉ ČINNOSTI PRO ROSTLINNOU VÝROBU" },
  { code: '16200', name: "PODPŮRNÉ ČINNOSTI PRO ŽIVOČIŠNOU VÝROBU" },
  { code: '16300', name: "POSKLIZŇOVÉ ČINNOSTI A ZPRACOVÁNÍ OSIVA PRO ÚČELY MNOŽENÍ" },
  { code: '17000', name: "LOV A ODCHYT DIVOKÝCH ZVÍŘAT A SOUVISEJÍCÍ ČINNOSTI" },
  { code: '20000', name: "LESNICTVÍ A TĚŽBA DŘEVA" },
  { code: '21000', name: "PĚSTOVÁNÍ LESA A JINÉ ČINNOSTI V OBLASTI LESNICTVÍ" },
  { code: '22000', name: "TĚŽBA DŘEVA" },
  { code: '23000', name: "SBĚR A ZÍSKÁVÁNÍ VOLNĚ ROSTOUCÍCH PLODŮ A MATERIÁLŮ, KROMĚ DŘEVA" },
  { code: '24000', name: "PODPŮRNÉ ČINNOSTI PRO LESNICTVÍ" },
  { code: '30000', name: "RYBOLOV A AKVAKULTURA" },
  { code: '31000', name: "RYBOLOV" },
  { code: '31100', name: "MOŘSKÝ RYBOLOV" },
  { code: '31200', name: "SLADKOVODNÍ RYBOLOV" },
  { code: '32000', name: "AKVAKULTURA" },
  { code: '32100', name: "MOŘSKÁ AKVAKULTURA" },
  { code: '32200', name: "SLADKOVODNÍ AKVAKULTURA" },
  { code: '33000', name: "PODPŮRNÉ ČINNOSTI PRO RYBOLOV A AKVAKULTURU" },
  { code: '50000', name: "TĚŽBA ČERNÉHO A HNĚDÉHO UHLÍ" },
  { code: '51000', name: "TĚŽBA ČERNÉHO UHLÍ" },
  { code: '51010', name: "TĚŽBA ČERNÉHO UHLÍ, KROMĚ ÚPRAVY" },
  { code: '51020', name: "ÚPRAVA ČERNÉHO UHLÍ" },
  { code: '52000', name: "TĚŽBA HNĚDÉHO UHLÍ" },
  { code: '52010', name: "TĚŽBA HNĚDÉHO UHLÍ JINÉHO NEŽ LIGNITU, KROMĚ ÚPRAVY" },
  { code: '52020', name: "ÚPRAVA HNĚDÉHO UHLÍ JINÉHO NEŽ LIGNITU" },
  { code: '52030', name: "TĚŽBA LIGNITU, KROMĚ ÚPRAVY" },
  { code: '52040', name: "ÚPRAVA LIGNITU" },
  { code: '60000', name: "TĚŽBA ROPY A ZEMNÍHO PLYNU" },
  { code: '61000', name: "TĚŽBA ROPY" },
  { code: '62000', name: "TĚŽBA ZEMNÍHO PLYNU" },
  { code: '70000', name: "TĚŽBA RUD" },
  { code: '71000', name: "TĚŽBA ŽELEZNÝCH RUD" },
  { code: '71010', name: "TĚŽBA ŽELEZNÝCH RUD, KROMĚ ÚPRAVY" },
  { code: '71020', name: "ÚPRAVA ŽELEZNÝCH RUD" },
  { code: '72000', name: "TĚŽBA NEŽELEZNÝCH RUD" },
  { code: '72100', name: "TĚŽBA URANOVÝCH A THORIOVÝCH RUD" },
  { code: '72110', name: "TĚŽBA URANOVÝCH A THORIOVÝCH RUD, KROMĚ ÚPRAVY" },
  { code: '72120', name: "ÚPRAVA URANOVÝCH A THORIOVÝCH RUD" },
  { code: '72900', name: "TĚŽBA OSTATNÍCH NEŽELEZNÝCH RUD" },
  { code: '72910', name: "TĚŽBA OSTATNÍCH NEŽELEZNÝCH RUD, KROMĚ ÚPRAVY" },
  { code: '72920', name: "ÚPRAVA OSTATNÍCH NEŽELEZNÝCH RUD" },
  { code: '80000', name: "TĚŽBA A DOBÝVÁNÍ OSTATNÍCH NEROSTNÝCH SUROVIN" },
  { code: '81000', name: "DOBÝVÁNÍ KAMENE, PÍSKŮ A JÍLŮ" },
  { code: '81100', name: "DOBÝVÁNÍ KAMENE, VÁPENCE, SÁDROVCE, BŘIDLICE A JINÉHO KAMENE, TAKÉ PRO VÝTVARNÉ ÚČELY" },
  { code: '81200', name: "PROVOZ PÍSKOVEN A ŠTĚRKOPÍSKOVEN A TĚŽBA JÍLŮ A KAOLINU" },
  { code: '89000', name: "TĚŽBA A DOBÝVÁNÍ NEROSTNÝCH SUROVIN J. N." },
  { code: '89100', name: "TĚŽBA CHEMICKÝCH MINERÁLŮ A MINERÁLŮ PRO VÝROBU HNOJIV" },
  { code: '89200', name: "TĚŽBA RAŠELINY" },
  { code: '89300', name: "TĚŽBA SOLI" },
  { code: '89900', name: "TĚŽBA A DOBÝVÁNÍ OSTATNÍCH NEROSTNÝCH SUROVIN J. N." },
  { code: '90000', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU A DOBÝVÁNÍ NEROSTNÝCH SUROVIN" },
  { code: '91000', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU ROPY A ZEMNÍHO PLYNU" },
  { code: '99000', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU A DOBÝVÁNÍ OSTATNÍCH NEROSTNÝCH SUROVIN" },
  { code: '99010', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU ČERNÉHO UHLÍ" },
  { code: '99020', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU HNĚDÉHO UHLÍ, KROMĚ LIGNITU" },
  { code: '99030', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU LIGNITU" },
  { code: '99040', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU ŽELEZNÝCH RUD" },
  { code: '99050', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU URANOVÝCH A THORIOVÝCH RUD" },
  { code: '99060', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU OSTATNÍCH NEŽELEZNÝCH RUD" },
  { code: '99090', name: "PODPŮRNÉ ČINNOSTI PRO TĚŽBU A DOBÝVÁNÍ OSTATNÍCH NEROSTNÝCH SUROVIN J. N." },
]
