// Číselník CZ-NACE 2025 (opravená systematická část, prosinec 2025)
// Zdroj: Český statistický úřad — https://csu.gov.cz/klasifikace-ekonomickych-cinnosti-cz-nace-platna-od-1-1-2025
// Formát: 6 znaků, kód bez teček doplněný nulami zprava (viz podpora.mojedane.gov.cz)
export interface NaceEntry { code: string; name: string }

export const NACE_CODES: NaceEntry[] = [
  { code: '010000', name: "Rostlinná a živočišná výroba, myslivost a související činnosti" },
  { code: '011000', name: "Pěstování plodin jiných než trvalých" },
  { code: '011100', name: "Pěstování obilovin jiných než rýže, luštěnin a olejnatých semen" },
  { code: '011200', name: "Pěstování rýže" },
  { code: '011300', name: "Pěstování zeleniny a melounů, kořenů a hlíz" },
  { code: '011400', name: "Pěstování cukrové třtiny" },
  { code: '011500', name: "Pěstování tabáku" },
  { code: '011600', name: "Pěstování přadných rostlin" },
  { code: '011900', name: "Pěstování ostatních plodin jiných než trvalých" },
  { code: '012000', name: "Pěstování trvalých plodin" },
  { code: '012100', name: "Pěstování vinných hroznů" },
  { code: '012200', name: "Pěstování tropického a subtropického ovoce" },
  { code: '012300', name: "Pěstování citrusových plodů" },
  { code: '012400', name: "Pěstování jádrového a peckového ovoce" },
  { code: '012500', name: "Pěstování ostatního stromového a keřového ovoce a ořechů" },
  { code: '012600', name: "Pěstování olejnatých plodů" },
  { code: '012700', name: "Pěstování rostlin pro výrobu nápojů" },
  { code: '012800', name: "Pěstování koření a aromatických, léčivých a farmaceutických rostlin" },
  { code: '012900', name: "Pěstování ostatních trvalých plodin" },
  { code: '013000', name: "Množení rostlin" },
  { code: '014000', name: "Živočišná výroba" },
  { code: '014100', name: "Chov mléčného skotu" },
  { code: '014200', name: "Chov ostatního skotu a buvolů" },
  { code: '014300', name: "Chov koní a ostatních koňovitých" },
  { code: '014400', name: "Chov velbloudů a velbloudovitých" },
  { code: '014500', name: "Chov ovcí a koz" },
  { code: '014600', name: "Chov prasat" },
  { code: '014700', name: "Chov drůbeže" },
  { code: '014800', name: "Chov ostatních zvířat" },
  { code: '015000', name: "Smíšené hospodaření" },
  { code: '016000', name: "Podpůrné činnosti pro zemědělství a posklizňové činnosti" },
  { code: '016100', name: "Podpůrné činnosti pro rostlinnou výrobu" },
  { code: '016200', name: "Podpůrné činnosti pro živočišnou výrobu" },
  { code: '016300', name: "Posklizňové činnosti a zpracování osiva pro účely množení" },
  { code: '017000', name: "Lov a odchyt divokých zvířat a související činnosti" },
  { code: '020000', name: "Lesnictví a těžba dřeva" },
  { code: '021000', name: "Pěstování lesa a jiné činnosti v oblasti lesnictví" },
  { code: '022000', name: "Těžba dřeva" },
  { code: '023000', name: "Sběr a získávání volně rostoucích plodů a materiálů, kromě dřeva" },
  { code: '024000', name: "Podpůrné činnosti pro lesnictví" },
  { code: '030000', name: "Rybolov a akvakultura" },
  { code: '031000', name: "Rybolov" },
  { code: '031100', name: "Mořský rybolov" },
  { code: '031200', name: "Sladkovodní rybolov" },
  { code: '032000', name: "Akvakultura" },
  { code: '032100', name: "Mořská akvakultura" },
  { code: '032200', name: "Sladkovodní akvakultura" },
  { code: '033000', name: "Podpůrné činnosti pro rybolov a akvakulturu" },
  { code: '050000', name: "Těžba černého a hnědého uhlí" },
  { code: '051000', name: "Těžba černého uhlí" },
  { code: '052000', name: "Těžba hnědého uhlí" },
  { code: '060000', name: "Těžba ropy a zemního plynu" },
  { code: '061000', name: "Těžba ropy" },
  { code: '062000', name: "Těžba zemního plynu" },
  { code: '070000', name: "Těžba rud" },
  { code: '071000', name: "Těžba železných rud" },
  { code: '072000', name: "Těžba neželezných rud" },
  { code: '072100', name: "Těžba uranových a thoriových rud" },
  { code: '072900', name: "Těžba ostatních neželezných rud" },
  { code: '080000', name: "Těžba a dobývání ostatních nerostných surovin" },
  { code: '081000', name: "Dobývání kamene, písků a jílů" },
  { code: '081100', name: "Dobývání kamene, vápence, sádrovce, břidlice a jiného kamene, také pro výtvarné účely" },
  { code: '081200', name: "Provoz pískoven a štěrkopískoven a těžba jílů a kaolinu" },
  { code: '089000', name: "Těžba a dobývání nerostných surovin j. n." },
  { code: '089100', name: "Těžba chemických minerálů a minerálů pro výrobu hnojiv" },
  { code: '089200', name: "Těžba rašeliny" },
  { code: '089300', name: "Těžba soli" },
  { code: '089900', name: "Těžba a dobývání ostatních nerostných surovin j. n." },
  { code: '090000', name: "Podpůrné činnosti pro těžbu a dobývání nerostných surovin" },
  { code: '091000', name: "Podpůrné činnosti pro těžbu ropy a zemního plynu" },
  { code: '099000', name: "Podpůrné činnosti pro těžbu a dobývání ostatních nerostných surovin" },
  { code: '100000', name: "Výroba potravinářských výrobků" },
  { code: '101000', name: "Zpracování a konzervování masa a výroba masných výrobků" },
  { code: '101100', name: "Zpracování a konzervování masa, kromě drůbežího masa" },
  { code: '101200', name: "Zpracování a konzervování drůbežího masa" },
  { code: '101300', name: "Výroba masných výrobků a výrobků z drůbežího masa" },
  { code: '102000', name: "Zpracování a konzervování ryb, korýšů a měkkýšů" },
  { code: '103000', name: "Zpracování a konzervování ovoce a zeleniny" },
  { code: '103100', name: "Zpracování a konzervování brambor" },
  { code: '103200', name: "Výroba ovocných a zeleninových šťáv" },
  { code: '103900', name: "Ostatní zpracování a konzervování ovoce a zeleniny" },
  { code: '104000', name: "Výroba rostlinných a živočišných olejů a tuků" },
  { code: '104100', name: "Výroba olejů a tuků" },
  { code: '104200', name: "Výroba margarínu a podobných jedlých tuků" },
  { code: '105000', name: "Výroba mléčných výrobků, výroba zmrzliny a ledu k lidské spotřebě" },
  { code: '105100', name: "Výroba mléčných výrobků" },
  { code: '105200', name: "Výroba zmrzliny a ledu k lidské spotřebě" },
  { code: '106000', name: "Výroba mlýnských a škrobárenských výrobků" },
  { code: '106100', name: "Výroba mlýnských výrobků" },
  { code: '106200', name: "Výroba škrobárenských výrobků" },
  { code: '107000', name: "Výroba pekařských, cukrářských a jiných moučných výrobků" },
  { code: '107100', name: "Výroba pekařských a cukrářských výrobků, kromě trvanlivých" },
  { code: '107200', name: "Výroba sucharů, sušenek a trvanlivých pekařských a cukrářských výrobků" },
  { code: '107300', name: "Výroba moučných výrobků" },
  { code: '108000', name: "Výroba ostatních potravinářských výrobků" },
  { code: '108100', name: "Výroba cukru" },
  { code: '108200', name: "Výroba kakaa, čokolády a cukrovinek" },
  { code: '108300', name: "Zpracování čaje a kávy" },
  { code: '108400', name: "Výroba koření a přísad pro ochucení" },
  { code: '108500', name: "Výroba hotových pokrmů" },
  { code: '108600', name: "Výroba homogenizovaných potravinářských přípravků a dietetických potravin" },
  { code: '108900', name: "Výroba ostatních potravinářských výrobků j. n." },
  { code: '109000', name: "Výroba krmiv" },
  { code: '109100', name: "Výroba krmiv pro hospodářská zvířata" },
  { code: '109200', name: "Výroba krmiv pro zvířata v zájmovém chovu" },
  { code: '110000', name: "Výroba nápojů" },
  { code: '110100', name: "Destilace, rektifikace a míchaní lihovin" },
  { code: '110200', name: "Výroba vína z vinných hroznů" },
  { code: '110300', name: "Výroba ciderů a jiných kvašených ovocných nápojů" },
  { code: '110400', name: "Výroba ostatních nedestilovaných kvašených nápojů" },
  { code: '110500', name: "Výroba piva" },
  { code: '110600', name: "Výroba sladu" },
  { code: '110700', name: "Výroba nealkoholických nápojů a balených vod" },
  { code: '120000', name: "Výroba tabákových výrobků" },
  { code: '130000', name: "Výroba textilií" },
  { code: '131000', name: "Úprava a spřádání textilních vláken a příze" },
  { code: '132000', name: "Tkaní textilií" },
  { code: '133000', name: "Konečná úprava textilií" },
  { code: '139000', name: "Výroba ostatních textilií" },
  { code: '139100', name: "Výroba pletených a háčkovaných textilií" },
  { code: '139200', name: "Výroba bytového textilu a konfekčních bytových textilií" },
  { code: '139300', name: "Výroba koberců a kobercových předložek" },
  { code: '139400', name: "Výroba lan, provazů a síťovaných výrobků" },
  { code: '139500', name: "Výroba netkaných textilií a výrobků z nich" },
  { code: '139600', name: "Výroba ostatních technických a průmyslových textilií" },
  { code: '139900', name: "Výroba ostatních textilií j. n." },
  { code: '140000', name: "Výroba oděvů" },
  { code: '141000', name: "Výroba pletených a háčkovaných oděvů" },
  { code: '142000', name: "Výroba ostatních oděvů a oděvních doplňků" },
  { code: '142100', name: "Výroba svrchních oděvů" },
  { code: '142200', name: "Výroba osobního prádla" },
  { code: '142300', name: "Výroba pracovních oděvů" },
  { code: '142400', name: "Výroba kožených oděvů a kožešinových výrobků" },
  { code: '142900', name: "Výroba ostatních oděvů a oděvních doplňků j. n." },
  { code: '150000', name: "Výroba usní a souvisejících výrobků z jakýchkoli materiálů" },
  { code: '151000', name: "Činění, úprava, barvení usní a kožešin; výroba zavazadel, kabelek, sedlářských a řemenářských výrobků" },
  { code: '151100', name: "Činění, úprava, barvení usní a kožešin" },
  { code: '151200', name: "Výroba zavazadel, kabelek, sedlářských a řemenářských výrobků z jakýchkoli materiálů" },
  { code: '152000', name: "Výroba obuvi" },
  { code: '160000', name: "Zpracování dřeva, výroba dřevěných, korkových, proutěných a slaměných výrobků, kromě nábytku" },
  { code: '161000', name: "Pilařská výroba a impregnace dřeva; zpracování a konečná úprava dřeva" },
  { code: '161100', name: "Pilařská výroba" },
  { code: '161200', name: "Zpracování a konečná úprava dřeva" },
  { code: '162000', name: "Výroba dřevěných, korkových, proutěných a slaměných výrobků" },
  { code: '162100', name: "Výroba dýh a desek na bázi dřeva" },
  { code: '162200', name: "Výroba sestavených parketových podlah" },
  { code: '162300', name: "Výroba ostatních výrobků stavebního truhlářství a tesařství" },
  { code: '162400', name: "Výroba dřevěných obalů" },
  { code: '162500', name: "Výroba dřevěných dveří a oken" },
  { code: '162600', name: "Výroba pevných paliv z rostlinné biomasy" },
  { code: '162700', name: "Konečná úprava dřevěných výrobků" },
  { code: '162800', name: "Výroba ostatních dřevěných, korkových, proutěných a slaměných výrobků" },
  { code: '170000', name: "Výroba papíru a výrobků z papíru" },
  { code: '171000', name: "Výroba buničiny, papíru a lepenky" },
  { code: '171100', name: "Výroba buničiny" },
  { code: '171200', name: "Výroba papíru a lepenky" },
  { code: '172000', name: "Výroba výrobků z papíru a lepenky" },
  { code: '172100', name: "Výroba vlnitého papíru a lepenky, papírových a lepenkových obalů" },
  { code: '172200', name: "Výroba domácích potřeb, hygienických a toaletních výrobků z papíru" },
  { code: '172300', name: "Výroba kancelářských potřeb z papíru" },
  { code: '172400', name: "Výroba tapet" },
  { code: '172500', name: "Výroba ostatních výrobků z papíru a lepenky" },
  { code: '180000', name: "Tisk a rozmnožování nahraných nosičů" },
  { code: '181000', name: "Tisk a činnosti související s tiskem" },
  { code: '181100', name: "Tisk novin" },
  { code: '181200', name: "Ostatní tisk" },
  { code: '181300', name: "Příprava tisku a digitálních dat" },
  { code: '181400', name: "Vázání a související činnosti" },
  { code: '182000', name: "Rozmnožování nahraných nosičů" },
  { code: '190000', name: "Výroba koksu a rafinovaných ropných produktů" },
  { code: '191000', name: "Výroba koksárenských produktů" },
  { code: '192000', name: "Výroba rafinovaných ropných produktů a produktů z fosilních paliv" },
  { code: '200000', name: "Výroba chemických látek a chemických výrobků" },
  { code: '201000', name: "Výroba základních chemických látek, hnojiv a dusíkatých sloučenin, plastů a syntetického kaučuku v primárních formách" },
  { code: '201100', name: "Výroba technických plynů" },
  { code: '201200', name: "Výroba barviv a pigmentů" },
  { code: '201300', name: "Výroba jiných základních anorganických chemických látek" },
  { code: '201400', name: "Výroba jiných základních organických chemických látek" },
  { code: '201500', name: "Výroba hnojiv a dusíkatých sloučenin" },
  { code: '201600', name: "Výroba plastů v primárních formách" },
  { code: '201700', name: "Výroba syntetického kaučuku v primárních formách" },
  { code: '202000', name: "Výroba pesticidů, dezinfekčních prostředků a jiných agrochemických přípravků" },
  { code: '203000', name: "Výroba barev, laků a jiných nátěrových hmot, tiskařských barev a tmelů" },
  { code: '204000', name: "Výroba mycích, čisticích a lešticích prostředků" },
  { code: '204100', name: "Výroba mýdel, detergentů a čisticích a lešticích prostředků" },
  { code: '204200', name: "Výroba parfémů a toaletních přípravků" },
  { code: '205000', name: "Výroba ostatních chemických výrobků" },
  { code: '205100', name: "Výroba kapalných biopaliv" },
  { code: '205900', name: "Výroba ostatních chemických výrobků j. n." },
  { code: '206000', name: "Výroba chemických vláken" },
  { code: '210000', name: "Výroba základních farmaceutických výrobků a farmaceutických přípravků" },
  { code: '211000', name: "Výroba základních farmaceutických výrobků" },
  { code: '212000', name: "Výroba farmaceutických přípravků" },
  { code: '220000', name: "Výroba pryžových a plastových výrobků" },
  { code: '221000', name: "Výroba pryžových výrobků" },
  { code: '221100', name: "Výroba pryžových plášťů a duší a protektorování pneumatik" },
  { code: '221200', name: "Výroba ostatních pryžových výrobků" },
  { code: '222000', name: "Výroba plastových výrobků" },
  { code: '222100', name: "Výroba plastových desek, fólií, hadic, trubek a profilů" },
  { code: '222200', name: "Výroba plastových obalů" },
  { code: '222300', name: "Výroba plastových dveří a oken" },
  { code: '222400', name: "Výroba plastových výrobků pro stavebnictví" },
  { code: '222500', name: "Zpracování a konečná úprava plastových výrobků" },
  { code: '222600', name: "Výroba ostatních plastových výrobků" },
  { code: '230000', name: "Výroba ostatních nekovových minerálních výrobků" },
  { code: '231000', name: "Výroba skla a skleněných výrobků" },
  { code: '231100', name: "Výroba plochého skla" },
  { code: '231200', name: "Tvarování a zpracování plochého skla" },
  { code: '231300', name: "Výroba dutého skla" },
  { code: '231400', name: "Výroba skleněných vláken" },
  { code: '231500', name: "Výroba a zpracování ostatního skla, včetně technického skla" },
  { code: '232000', name: "Výroba žáruvzdorných výrobků" },
  { code: '233000', name: "Výroba stavebních výrobků z jílovitých materiálů" },
  { code: '233100', name: "Výroba keramických obkladaček a dlaždic" },
  { code: '233200', name: "Výroba pálených zdicích materiálů, tašek, dlaždic a podobných výrobků" },
  { code: '234000', name: "Výroba ostatních porcelánových a keramických výrobků" },
  { code: '234100', name: "Výroba porcelánových a keramických výrobků převážně pro domácnost a dekoračních předmětů" },
  { code: '234200', name: "Výroba keramických sanitárních výrobků" },
  { code: '234300', name: "Výroba keramických izolátorů a izolačního příslušenství" },
  { code: '234400', name: "Výroba ostatních technických keramických výrobků" },
  { code: '234500', name: "Výroba ostatních keramických výrobků" },
  { code: '235000', name: "Výroba cementu, vápna a sádry" },
  { code: '235100', name: "Výroba cementu" },
  { code: '235200', name: "Výroba vápna a sádry" },
  { code: '236000', name: "Výroba betonových, cementových a sádrových výrobků" },
  { code: '236100', name: "Výroba betonových výrobků pro stavební účely" },
  { code: '236200', name: "Výroba sádrových výrobků pro stavební účely" },
  { code: '236300', name: "Výroba betonu připraveného k lití" },
  { code: '236400', name: "Výroba malt" },
  { code: '236500', name: "Výroba vláknocementových výrobků" },
  { code: '236600', name: "Výroba ostatních betonových, cementových a sádrových výrobků" },
  { code: '237000', name: "Řezání, tvarování a konečná úprava kamenů" },
  { code: '239000', name: "Výroba brusiv a ostatních nekovových minerálních výrobků j. n." },
  { code: '239100', name: "Výroba brusiv" },
  { code: '239900', name: "Výroba ostatních nekovových minerálních výrobků j. n." },
  { code: '240000', name: "Výroba základních kovů" },
  { code: '241000', name: "Výroba surového železa, oceli a feroslitin" },
  { code: '242000', name: "Výroba ocelových trub, trubek, dutých profilů a souvisejících potrubních tvarovek" },
  { code: '243000', name: "Výroba ostatních výrobků získaných primárním zpracováním oceli" },
  { code: '243100', name: "Tažení ocelových tyčí za studena" },
  { code: '243200', name: "Válcování ocelových úzkých pásů za studena" },
  { code: '243300', name: "Tváření ocelových profilů za studena" },
  { code: '243400', name: "Tažení ocelového drátu za studena" },
  { code: '244000', name: "Výroba a hutní zpracování drahých a jiných neželezných kovů" },
  { code: '244100', name: "Výroba a hutní zpracování drahých kovů" },
  { code: '244200', name: "Výroba a hutní zpracování hliníku" },
  { code: '244300', name: "Výroba a hutní zpracování olova, zinku a cínu" },
  { code: '244400', name: "Výroba a hutní zpracování mědi" },
  { code: '244500', name: "Výroba a hutní zpracování ostatních neželezných kovů" },
  { code: '244600', name: "Zpracování jaderného paliva" },
  { code: '245000', name: "Odlévání kovů" },
  { code: '245100', name: "Odlévání litiny" },
  { code: '245200', name: "Odlévání oceli" },
  { code: '245300', name: "Odlévání lehkých kovů" },
  { code: '245400', name: "Odlévání ostatních neželezných kovů" },
  { code: '250000', name: "Výroba kovových výrobků, kromě strojů a zařízení" },
  { code: '251000', name: "Výroba konstrukčních kovových výrobků" },
  { code: '251100', name: "Výroba kovových konstrukcí a jejich dílů" },
  { code: '251200', name: "Výroba kovových dveří a oken" },
  { code: '252000', name: "Výroba kovových cisteren, nádrží a podobných nádob" },
  { code: '252100', name: "Výroba radiátorů k ústřednímu topení a parních kotlů" },
  { code: '252200', name: "Výroba ostatních kovových cisteren, nádrží a podobných nádob" },
  { code: '253000', name: "Výroba zbraní a střeliva" },
  { code: '254000', name: "Kování a tváření kovů a prášková metalurgie" },
  { code: '255000', name: "Povrchové úpravy a zušlechťování kovů; obrábění" },
  { code: '255100', name: "Povlakování kovů" },
  { code: '255200', name: "Tepelné zpracování kovů" },
  { code: '255300', name: "Obrábění kovů" },
  { code: '256000', name: "Výroba nožířských výrobků, nástrojů a železářských výrobků" },
  { code: '256100', name: "Výroba nožířských výrobků" },
  { code: '256200', name: "Výroba zámků a kování" },
  { code: '256300', name: "Výroba nástrojů a nářadí" },
  { code: '259000', name: "Výroba ostatních kovových výrobků" },
  { code: '259100', name: "Výroba ocelových sudů a podobných nádob" },
  { code: '259200', name: "Výroba obalů z lehkých kovů" },
  { code: '259300', name: "Výroba drátěných výrobků, řetězů a pružin" },
  { code: '259400', name: "Výroba spojovacích materiálů a výrobků se závity" },
  { code: '259900', name: "Výroba ostatních kovových výrobků j. n." },
  { code: '260000', name: "Výroba počítačů a elektronických a optických přístrojů a zařízení" },
  { code: '261000', name: "Výroba elektronických součástek a desek" },
  { code: '261100', name: "Výroba elektronických součástek" },
  { code: '261200', name: "Výroba osazených elektronických desek" },
  { code: '262000', name: "Výroba počítačů a periferních zařízení" },
  { code: '263000', name: "Výroba komunikačních zařízení" },
  { code: '264000', name: "Výroba spotřební elektroniky" },
  { code: '265000', name: "Výroba měřicích, zkušebních a časoměrných přístrojů" },
  { code: '265100', name: "Výroba měřicích, zkušebních a navigačních přístrojů" },
  { code: '265200', name: "Výroba časoměrných přístrojů" },
  { code: '266000', name: "Výroba ozařovacích, elektroléčebných a elektroterapeutických přístrojů" },
  { code: '267000', name: "Výroba optických přístrojů a zařízení, magnetických a optických médií a fotografických přístrojů a zařízení" },
  { code: '270000', name: "Výroba elektrických zařízení" },
  { code: '271000', name: "Výroba elektrických motorů, generátorů, transformátorů a elektrických rozvodných a kontrolních zařízení" },
  { code: '271100', name: "Výroba elektrických motorů, generátorů a transformátorů" },
  { code: '271200', name: "Výroba elektrických rozvodných a kontrolních zařízení" },
  { code: '272000', name: "Výroba baterií a akumulátorů" },
  { code: '273000', name: "Výroba optických a elektrických kabelů, elektrických vodičů a elektroinstalačních zařízení" },
  { code: '273100', name: "Výroba optických kabelů" },
  { code: '273200', name: "Výroba ostatních elektronických a elektrických vodičů a kabelů" },
  { code: '273300', name: "Výroba elektroinstalačních zařízení" },
  { code: '274000', name: "Výroba osvětlovacích zařízení" },
  { code: '275000', name: "Výroba spotřebičů převážně pro domácnost" },
  { code: '275100', name: "Výroba elektrických spotřebičů převážně pro domácnost" },
  { code: '275200', name: "Výroba neelektrických spotřebičů převážně pro domácnost" },
  { code: '279000', name: "Výroba ostatních elektrických zařízení" },
  { code: '280000', name: "Výroba strojů a zařízení j. n." },
  { code: '281000', name: "Výroba strojů a zařízení pro všeobecné účely" },
  { code: '281100', name: "Výroba motorů a turbín, kromě motorů pro letadla, automobily a motocykly" },
  { code: '281200', name: "Výroba hydraulických zařízení" },
  { code: '281300', name: "Výroba ostatních čerpadel a kompresorů" },
  { code: '281400', name: "Výroba ostatních potrubních armatur" },
  { code: '281500', name: "Výroba ložisek, ozubených kol, převodů a hnacích prvků" },
  { code: '282000', name: "Výroba ostatních strojů a zařízení pro všeobecné účely" },
  { code: '282100', name: "Výroba pecí, kotlů a stálých tepelných zařízení pro domácnosti" },
  { code: '282200', name: "Výroba zdvihacích a manipulačních zařízení" },
  { code: '282300', name: "Výroba kancelářských strojů a zařízení, kromě počítačů a periferních zařízení" },
  { code: '282400', name: "Výroba ručních mechanizovaných nástrojů" },
  { code: '282500', name: "Výroba klimatizačních zařízení jiných než pro domácnost" },
  { code: '282900', name: "Výroba ostatních strojů a zařízení pro všeobecné účely j. n." },
  { code: '283000', name: "Výroba zemědělských a lesnických strojů" },
  { code: '284000', name: "Výroba tvářecích strojů na opracování kovů a obráběcích strojů" },
  { code: '284100', name: "Výroba tvářecích a obráběcích strojů na opracování kovů" },
  { code: '284200', name: "Výroba ostatních obráběcích strojů" },
  { code: '289000', name: "Výroba ostatních strojů pro speciální účely" },
  { code: '289100', name: "Výroba strojů pro metalurgii" },
  { code: '289200', name: "Výroba strojů pro těžbu, dobývání a stavebnictví" },
  { code: '289300', name: "Výroba strojů na výrobu potravin, nápojů a zpracování tabáku" },
  { code: '289400', name: "Výroba strojů na výrobu textilu, oděvních výrobků a výrobků z usní" },
  { code: '289500', name: "Výroba strojů a přístrojů na výrobu papíru a lepenky" },
  { code: '289600', name: "Výroba strojů na výrobu plastů a pryže" },
  { code: '289700', name: "Výroba strojů pro aditivní výrobu" },
  { code: '289900', name: "Výroba ostatních strojů pro speciální účely j. n." },
  { code: '290000', name: "Výroba motorových vozidel, přívěsů a návěsů" },
  { code: '291000', name: "Výroba motorových vozidel" },
  { code: '292000', name: "Výroba karoserií motorových vozidel; výroba přívěsů a návěsů" },
  { code: '293000', name: "Výroba dílů a příslušenství pro motorová vozidla" },
  { code: '293100', name: "Výroba elektrického a elektronického zařízení pro motorová vozidla" },
  { code: '293200', name: "Výroba ostatních dílů a příslušenství pro motorová vozidla" },
  { code: '300000', name: "Výroba ostatních dopravních prostředků a zařízení" },
  { code: '301000', name: "Stavba lodí a člunů" },
  { code: '301100', name: "Stavba civilních lodí a plavidel" },
  { code: '301200', name: "Stavba rekreačních a sportovních člunů" },
  { code: '301300', name: "Stavba vojenských lodí a plavidel" },
  { code: '302000', name: "Výroba železničních lokomotiv a kolejových vozidel" },
  { code: '303000', name: "Výroba letadel, kosmických lodí a souvisejících zařízení" },
  { code: '303100', name: "Výroba civilních letadel, kosmických lodí a souvisejících zařízení" },
  { code: '303200', name: "Výroba vojenských letadel, kosmických lodí a souvisejících zařízení" },
  { code: '304000', name: "Výroba vojenských bojových vozidel" },
  { code: '309000', name: "Výroba dopravních prostředků a zařízení j. n." },
  { code: '309100', name: "Výroba motocyklů" },
  { code: '309200', name: "Výroba jízdních kol a vozíků pro invalidy" },
  { code: '309900', name: "Výroba ostatních dopravních prostředků a zařízení j. n." },
  { code: '310000', name: "Výroba nábytku" },
  { code: '320000', name: "Ostatní zpracovatelský průmysl" },
  { code: '321000', name: "Výroba klenotů, bižuterie a příbuzných výrobků" },
  { code: '321100', name: "Ražení mincí" },
  { code: '321200', name: "Výroba klenotů a příbuzných výrobků" },
  { code: '321300', name: "Výroba bižuterie a příbuzných výrobků" },
  { code: '322000', name: "Výroba hudebních nástrojů" },
  { code: '323000', name: "Výroba sportovních potřeb" },
  { code: '324000', name: "Výroba her a hraček" },
  { code: '325000', name: "Výroba lékařských a dentálních nástrojů a potřeb" },
  { code: '329000', name: "Zpracovatelský průmysl j. n." },
  { code: '329100', name: "Výroba košťat a kartáčnických výrobků" },
  { code: '329900', name: "Ostatní zpracovatelský průmysl j. n." },
  { code: '330000', name: "Opravy, údržba a instalace strojů a zařízení" },
  { code: '331000', name: "Opravy a údržba kovových výrobků, strojů a zařízení" },
  { code: '331100', name: "Opravy a údržba kovových výrobků" },
  { code: '331200', name: "Opravy a údržba strojů" },
  { code: '331300', name: "Opravy a údržba elektronických a optických přístrojů a zařízení" },
  { code: '331400', name: "Opravy a údržba elektrických zařízení" },
  { code: '331500', name: "Opravy a údržba civilních lodí a člunů" },
  { code: '331600', name: "Opravy a údržba civilních letadel a kosmických lodí" },
  { code: '331700', name: "Opravy a údržba ostatních civilních dopravních prostředků a zařízení" },
  { code: '331800', name: "Opravy a údržba vojenských bojových vozidel, lodí, člunů, letadel a kosmických lodí" },
  { code: '331900', name: "Opravy a údržba ostatních zařízení" },
  { code: '332000', name: "Instalace průmyslových strojů a zařízení" },
  { code: '350000', name: "Dodávání elektřiny, plynu, páry a klimatizovaného vzduchu" },
  { code: '351000', name: "Výroba, přenos a distribuce elektřiny" },
  { code: '351100', name: "Výroba elektřiny z neobnovitelných zdrojů" },
  { code: '351200', name: "Výroba elektřiny z obnovitelných zdrojů" },
  { code: '351300', name: "Přenos elektřiny" },
  { code: '351400', name: "Distribuce elektřiny" },
  { code: '351500', name: "Obchod s elektřinou" },
  { code: '351600', name: "Skladování elektřiny" },
  { code: '352000', name: "Výroba plynu a distribuce plynných paliv prostřednictvím sítí" },
  { code: '352100', name: "Výroba plynu" },
  { code: '352200', name: "Distribuce plynných paliv prostřednictvím sítí" },
  { code: '352300', name: "Obchod s plynem prostřednictvím sítí" },
  { code: '352400', name: "Skladování plynu jako součást služeb síťových dodávek" },
  { code: '353000', name: "Dodávání páry a klimatizovaného vzduchu" },
  { code: '354000', name: "Činnosti makléřů a agentů v oblasti elektrické energie a zemního plynu" },
  { code: '360000', name: "Shromažďování, úprava a distribuce vody" },
  { code: '370000', name: "Činnosti související s odpadními vodami" },
  { code: '380000', name: "Sběr odpadů, zpracování odpadů k dalšímu využití a odstraňování odpadů" },
  { code: '381000', name: "Sběr odpadů" },
  { code: '381100', name: "Sběr odpadů, kromě nebezpečných" },
  { code: '381200', name: "Sběr nebezpečných odpadů" },
  { code: '382000', name: "Zpracování odpadů k dalšímu využití" },
  { code: '382100', name: "Zpracování odpadů k získání materiálů k dalšímu využití" },
  { code: '382200', name: "Zpracování odpadů k energetickému využití" },
  { code: '382300', name: "Zpracování odpadů k ostatnímu využití" },
  { code: '383000', name: "Odstraňování odpadů bez dalšího využití" },
  { code: '383100', name: "Spalování odpadů bez energetického využití" },
  { code: '383200', name: "Skládkování nebo trvalé uložení odpadů" },
  { code: '383300', name: "Ostatní odstraňování odpadů" },
  { code: '390000', name: "Sanace a jiné činnosti související s odpady" },
  { code: '410000', name: "Výstavba bytových a nebytových budov" },
  { code: '420000', name: "Výstavba inženýrských děl" },
  { code: '421000', name: "Výstavba silnic a železnic" },
  { code: '421100', name: "Výstavba silnic a dálnic" },
  { code: '421200', name: "Výstavba železnic a podzemních drah" },
  { code: '421300', name: "Výstavba mostů a tunelů" },
  { code: '422000', name: "Výstavba inženýrských sítí" },
  { code: '422100', name: "Výstavba inženýrských sítí pro kapaliny a plyny" },
  { code: '422200', name: "Výstavba inženýrských sítí pro elektřinu a telekomunikace" },
  { code: '429000', name: "Výstavba ostatních inženýrských děl" },
  { code: '429100', name: "Výstavba vodních děl" },
  { code: '429900', name: "Výstavba ostatních inženýrských děl j. n." },
  { code: '430000', name: "Specializované stavební činnosti" },
  { code: '431000', name: "Demolice a příprava staveniště" },
  { code: '431100', name: "Demolice" },
  { code: '431200', name: "Příprava staveniště" },
  { code: '431300', name: "Průzkumné vrtné práce" },
  { code: '432000', name: "Elektroinstalační, instalatérské a ostatní stavebně instalační činnosti" },
  { code: '432100', name: "Elektrické instalace" },
  { code: '432200', name: "Instalace rozvodů vody, odpadu, topení a klimatizace" },
  { code: '432300', name: "Instalace izolací" },
  { code: '432400', name: "Ostatní stavební instalace" },
  { code: '433000', name: "Kompletační a dokončovací stavební práce" },
  { code: '433100', name: "Omítkářské práce" },
  { code: '433200', name: "Truhlářské práce" },
  { code: '433300', name: "Obkládání stěn a pokládání podlahových krytin" },
  { code: '433400', name: "Sklenářské, malířské a natěračské práce" },
  { code: '433500', name: "Ostatní kompletační a dokončovací stavební práce" },
  { code: '434000', name: "Specializované stavební činnosti při výstavbě budov" },
  { code: '434100', name: "Pokrývačské práce" },
  { code: '434200', name: "Ostatní specializované stavební činnosti při výstavbě budov" },
  { code: '435000', name: "Specializované stavební činnosti při výstavbě inženýrských děl" },
  { code: '436000', name: "Zprostředkování v oblasti specializovaných stavebních činností" },
  { code: '439000', name: "Ostatní specializované stavební činnosti" },
  { code: '439100', name: "Zednické práce" },
  { code: '439900', name: "Ostatní specializované stavební činnosti j. n." },
  { code: '460000', name: "Velkoobchod" },
  { code: '461000', name: "Zprostředkování v oblasti velkoobchodu za provizi" },
  { code: '461100', name: "Zprostředkování v oblasti velkoobchodu za provizi se základními zemědělskými produkty, živými zvířaty, textilními surovinami a polotovary" },
  { code: '461200', name: "Zprostředkování v oblasti velkoobchodu za provizi s palivy, rudami, kovy a technickými chemikáliemi" },
  { code: '461300', name: "Zprostředkování v oblasti velkoobchodu za provizi se dřevem a stavebními materiály" },
  { code: '461400', name: "Zprostředkování v oblasti velkoobchodu za provizi se stroji, průmyslovým zařízením, loděmi a letadly" },
  { code: '461500', name: "Zprostředkování v oblasti velkoobchodu za provizi s nábytkem, železářským zbožím a potřebami převážně pro domácnost" },
  { code: '461600', name: "Zprostředkování v oblasti velkoobchodu za provizi s textilem, oděvy, kožešinami, obuví a koženými výrobky" },
  { code: '461700', name: "Zprostředkování v oblasti velkoobchodu za provizi s potravinami, nápoji a tabákovými výrobky" },
  { code: '461800', name: "Zprostředkování v oblasti specializovaného velkoobchodu za provizi s ostatním zbožím" },
  { code: '461900', name: "Zprostředkování v oblasti nespecializovaného velkoobchodu za provizi" },
  { code: '462000', name: "Velkoobchod se základními zemědělskými produkty a živými zvířaty" },
  { code: '462100', name: "Velkoobchod s obilím, surovým tabákem, osivy a krmivy" },
  { code: '462200', name: "Velkoobchod s květinami a jinými rostlinami" },
  { code: '462300', name: "Velkoobchod s živými zvířaty" },
  { code: '462400', name: "Velkoobchod se surovými kůžemi, kožešinami a usněmi" },
  { code: '463000', name: "Velkoobchod s potravinami, nápoji a tabákovými výrobky" },
  { code: '463100', name: "Velkoobchod s ovocem a zeleninou" },
  { code: '463200', name: "Velkoobchod s masem, masnými výrobky, rybami a rybími výrobky" },
  { code: '463300', name: "Velkoobchod s mléčnými výrobky, vejci, jedlými oleji a tuky" },
  { code: '463400', name: "Velkoobchod s nápoji" },
  { code: '463500', name: "Velkoobchod s tabákovými výrobky" },
  { code: '463600', name: "Velkoobchod s cukrem, čokoládou a cukrovinkami" },
  { code: '463700', name: "Velkoobchod s kávou, čajem, kakaem a kořením" },
  { code: '463800', name: "Specializovaný velkoobchod s ostatními potravinami" },
  { code: '463900', name: "Nespecializovaný velkoobchod s potravinami, nápoji a tabákovými výrobky" },
  { code: '464000', name: "Velkoobchod s výrobky převážně pro domácnost" },
  { code: '464100', name: "Velkoobchod s textilem" },
  { code: '464200', name: "Velkoobchod s oděvy a obuví" },
  { code: '464300', name: "Velkoobchod s elektrospotřebiči a elektronikou převážně pro domácnost" },
  { code: '464400', name: "Velkoobchod s porcelánovými, keramickými a skleněnými výrobky a čisticími prostředky" },
  { code: '464500', name: "Velkoobchod s parfémy a kosmetickými přípravky" },
  { code: '464600', name: "Velkoobchod s farmaceutickými a zdravotnickými výrobky" },
  { code: '464700', name: "Velkoobchod s nábytkem, koberci a osvětlovacími zařízeními pro domácnosti, kanceláře a obchody" },
  { code: '464800', name: "Velkoobchod s hodinami, hodinkami a klenoty" },
  { code: '464900', name: "Velkoobchod s ostatními výrobky převážně pro domácnost" },
  { code: '465000', name: "Velkoobchod s počítačovými a komunikačními zařízeními" },
  { code: '466000', name: "Velkoobchod s ostatními stroji, strojním zařízením a příslušenstvím" },
  { code: '466100', name: "Velkoobchod se zemědělskými stroji, strojním zařízením a příslušenstvím" },
  { code: '466200', name: "Velkoobchod s obráběcími stroji" },
  { code: '466300', name: "Velkoobchod s těžebními a stavebními stroji a zařízením" },
  { code: '466400', name: "Velkoobchod s ostatními stroji a zařízením" },
  { code: '467000', name: "Velkoobchod s motorovými vozidly, motocykly, jejich díly a příslušenstvím" },
  { code: '467100', name: "Velkoobchod s motorovými vozidly" },
  { code: '467200', name: "Velkoobchod s díly a příslušenstvím pro motorová vozidla" },
  { code: '467300', name: "Velkoobchod s motocykly a jejich díly a příslušenstvím" },
  { code: '468000', name: "Ostatní specializovaný velkoobchod" },
  { code: '468100', name: "Velkoobchod s pevnými, kapalnými a plynnými palivy a příbuznými výrobky" },
  { code: '468200', name: "Velkoobchod s rudami, kovy a hutními výrobky" },
  { code: '468300', name: "Velkoobchod se dřevem, stavebními materiály a sanitárním vybavením" },
  { code: '468400', name: "Velkoobchod s železářským zbožím a instalatérskými a topenářskými potřebami" },
  { code: '468500', name: "Velkoobchod s chemickými výrobky" },
  { code: '468600', name: "Velkoobchod s ostatními meziprodukty" },
  { code: '468700', name: "Velkoobchod s odpadem a šrotem" },
  { code: '468900', name: "Ostatní specializovaný velkoobchod j. n." },
  { code: '469000', name: "Nespecializovaný velkoobchod" },
  { code: '470000', name: "Maloobchod" },
  { code: '471000', name: "Nespecializovaný maloobchod" },
  { code: '471100', name: "Nespecializovaný maloobchod s převahou potravin, nápojů a tabákových výrobků" },
  { code: '471200', name: "Ostatní nespecializovaný maloobchod" },
  { code: '472000', name: "Maloobchod s potravinami, nápoji a tabákovými výrobky" },
  { code: '472100', name: "Maloobchod s ovocem a zeleninou" },
  { code: '472200', name: "Maloobchod s masem a masnými výrobky" },
  { code: '472300', name: "Maloobchod s rybami, korýši a měkkýši" },
  { code: '472400', name: "Maloobchod s pekařskými a cukrářskými výrobky a cukrovinkami" },
  { code: '472500', name: "Maloobchod s nápoji" },
  { code: '472600', name: "Maloobchod s tabákovými výrobky" },
  { code: '472700', name: "Specializovaný maloobchod s ostatními potravinami" },
  { code: '473000', name: "Maloobchod s pohonnými hmotami" },
  { code: '474000', name: "Maloobchod s počítačovým a komunikačním zařízením" },
  { code: '475000', name: "Maloobchod s ostatními výrobky převážně pro domácnost" },
  { code: '475100', name: "Maloobchod s textilem" },
  { code: '475200', name: "Maloobchod s železářským zbožím, stavebními materiály, barvami a sklem" },
  { code: '475300', name: "Maloobchod s koberci, podlahovými krytinami a nástěnnými obklady" },
  { code: '475400', name: "Maloobchod s elektrospotřebiči a elektronikou převážně pro domácnost" },
  { code: '475500', name: "Maloobchod s nábytkem, osvětlovacími zařízeními, nádobím a ostatními výrobky převážně pro domácnost" },
  { code: '476000', name: "Maloobchod s výrobky pro kulturní rozhled a rekreaci" },
  { code: '476100', name: "Maloobchod s knihami" },
  { code: '476200', name: "Maloobchod s novinami a ostatními periodickými publikacemi a papírnickým zbožím" },
  { code: '476300', name: "Maloobchod se sportovním vybavením" },
  { code: '476400', name: "Maloobchod s hrami a hračkami" },
  { code: '476900', name: "Maloobchod s výrobky pro kulturní rozhled a rekreaci j. n." },
  { code: '477000', name: "Maloobchod s ostatním zbožím, kromě motorových vozidel a motocyklů" },
  { code: '477100', name: "Maloobchod s oděvy" },
  { code: '477200', name: "Maloobchod s obuví a koženými výrobky" },
  { code: '477300', name: "Maloobchod s farmaceutickými výrobky" },
  { code: '477400', name: "Maloobchod se zdravotnickými a ortopedickými výrobky" },
  { code: '477500', name: "Maloobchod s kosmetickými a toaletními výrobky" },
  { code: '477600', name: "Maloobchod s květinami, rostlinami, hnojivy, zvířaty pro zájmový chov a krmivy pro ně" },
  { code: '477700', name: "Maloobchod s hodinami, hodinkami a klenoty" },
  { code: '477800', name: "Maloobchod s ostatním novým zbožím" },
  { code: '477900', name: "Maloobchod s použitým zbožím" },
  { code: '478000', name: "Maloobchod s motorovými vozidly, motocykly, jejich díly a příslušenstvím" },
  { code: '478100', name: "Maloobchod s motorovými vozidly" },
  { code: '478200', name: "Maloobchod s díly a příslušenstvím pro motorová vozidla" },
  { code: '478300', name: "Maloobchod s motocykly a díly a příslušenstvím pro motocykly" },
  { code: '479000', name: "Zprostředkování v oblasti maloobchodu" },
  { code: '479100', name: "Zprostředkování v oblasti nespecializovaného maloobchodu" },
  { code: '479200', name: "Zprostředkování v oblasti specializovaného maloobchodu" },
  { code: '490000', name: "Pozemní a potrubní doprava" },
  { code: '491000', name: "Kolejová osobní doprava" },
  { code: '491100', name: "Dálková železniční osobní doprava" },
  { code: '491200', name: "Ostatní kolejová osobní doprava" },
  { code: '492000', name: "Kolejová nákladní doprava" },
  { code: '493000', name: "Ostatní pozemní osobní doprava" },
  { code: '493100', name: "Pravidelná silniční osobní doprava" },
  { code: '493200', name: "Nepravidelná silniční osobní doprava" },
  { code: '493300', name: "Osobní doprava vozidlem s řidičem na vyžádání" },
  { code: '493400', name: "Osobní doprava visutými lanovkami a lyžařskými vleky" },
  { code: '493900', name: "Ostatní pozemní osobní doprava j. n." },
  { code: '494000', name: "Silniční nákladní doprava a stěhovací služby" },
  { code: '494100', name: "Silniční nákladní doprava" },
  { code: '494200', name: "Stěhovací služby" },
  { code: '495000', name: "Potrubní doprava" },
  { code: '500000', name: "Vodní doprava" },
  { code: '501000', name: "Námořní a pobřežní osobní doprava" },
  { code: '502000', name: "Námořní a pobřežní nákladní doprava" },
  { code: '503000', name: "Vnitrozemská vodní osobní doprava" },
  { code: '504000', name: "Vnitrozemská vodní nákladní doprava" },
  { code: '510000', name: "Letecká doprava" },
  { code: '511000', name: "Letecká osobní doprava" },
  { code: '512000', name: "Letecká nákladní doprava a kosmická doprava" },
  { code: '512100', name: "Letecká nákladní doprava" },
  { code: '512200', name: "Kosmická doprava" },
  { code: '520000', name: "Skladování a podpůrné činnosti pro dopravu" },
  { code: '521000', name: "Skladování" },
  { code: '522000', name: "Podpůrné činnosti pro dopravu" },
  { code: '522100', name: "Činnosti související s pozemní dopravou" },
  { code: '522200', name: "Činnosti související s vodní dopravou" },
  { code: '522300', name: "Činnosti související s leteckou dopravou" },
  { code: '522400', name: "Manipulace s nákladem" },
  { code: '522500', name: "Logistické činnosti" },
  { code: '522600', name: "Ostatní podpůrné činnosti pro dopravu" },
  { code: '523000', name: "Zprostředkování v oblasti dopravy" },
  { code: '523100', name: "Zprostředkování v oblasti nákladní dopravy" },
  { code: '523200', name: "Zprostředkování v oblasti osobní dopravy" },
  { code: '530000', name: "Poštovní a kurýrní činnosti" },
  { code: '531000', name: "Základní poštovní služby poskytované na základě poštovní licence" },
  { code: '532000', name: "Ostatní poštovní a kurýrní činnosti" },
  { code: '533000', name: "Zprostředkování v oblasti poštovních a kurýrních činností" },
  { code: '550000', name: "Poskytování ubytování" },
  { code: '551000', name: "Ubytování v hotelích a podobných ubytovacích zařízeních" },
  { code: '552000', name: "Rekreační a ostatní krátkodobé ubytování" },
  { code: '553000', name: "Kempy a parkoviště pro rekreační vozidla" },
  { code: '554000', name: "Zprostředkování v oblasti ubytování" },
  { code: '559000', name: "Ostatní ubytování" },
  { code: '560000', name: "Poskytování stravování a podávání nápojů" },
  { code: '561000', name: "Poskytování stravování v restauracích, u stánků a mobilních zařízení" },
  { code: '561100', name: "Poskytování stravování v restauracích" },
  { code: '561200', name: "Poskytování stravování u stánků a mobilních zařízení" },
  { code: '562000', name: "Cateringové činnosti, poskytování smluvních a ostatních stravovacích služeb" },
  { code: '562100', name: "Cateringové činnosti" },
  { code: '562200', name: "Poskytování smluvních a ostatních stravovacích služeb" },
  { code: '563000', name: "Podávání nápojů" },
  { code: '564000', name: "Zprostředkování v oblasti stravování a podávání nápojů" },
  { code: '580000', name: "Vydavatelské činnosti" },
  { code: '581000', name: "Vydávání knih, novin a ostatní vydavatelské činnosti, kromě vydávání softwaru" },
  { code: '581100', name: "Vydávání knih" },
  { code: '581200', name: "Vydávání novin" },
  { code: '581300', name: "Vydávání časopisů a ostatních periodik" },
  { code: '581900', name: "Ostatní vydavatelské činnosti, kromě vydávání softwaru" },
  { code: '582000', name: "Vydávání softwaru" },
  { code: '582100', name: "Vydávání videoher" },
  { code: '582900', name: "Ostatní vydávání softwaru" },
  { code: '590000', name: "Činnosti v oblasti filmů, videozáznamů a televizních pořadů, pořizování zvukových nahrávek a hudební vydavatelské činnosti" },
  { code: '591000', name: "Činnosti v oblasti filmů, videozáznamů a televizních pořadů" },
  { code: '591100', name: "Produkce filmů, videozáznamů a televizních pořadů" },
  { code: '591200', name: "Postprodukce filmů, videozáznamů a televizních pořadů" },
  { code: '591300', name: "Distribuce filmů a videozáznamů" },
  { code: '591400', name: "Promítání filmů" },
  { code: '592000', name: "Pořizování zvukových nahrávek a hudební vydavatelské činnosti" },
  { code: '600000', name: "Tvorba programů, vysílání, činnosti zpravodajských tiskových kanceláří a agentur a ostatní činnosti související s distribucí obsahu" },
  { code: '601000', name: "Rozhlasové vysílání a distribuce zvukových záznamů" },
  { code: '602000', name: "Tvorba televizních programů, televizní vysílání a distribuce videozáznamů" },
  { code: '603000', name: "Činnosti zpravodajských kanceláří a agentur a ostatní činnosti související s distribucí obsahu" },
  { code: '603100', name: "Činnosti zpravodajských kanceláří a agentur" },
  { code: '603900', name: "Ostatní činnosti související s distribucí obsahu" },
  { code: '610000', name: "Telekomunikační činnosti" },
  { code: '611000', name: "Činnosti související s kabelovou, bezdrátovou a satelitní telekomunikační sítí" },
  { code: '612000', name: "Činnosti v oblasti přeprodeje telekomunikačních služeb a zprostředkování telekomunikačních činností" },
  { code: '619000', name: "Ostatní telekomunikační činnosti" },
  { code: '620000', name: "Počítačové programování, poradenství a související činnosti" },
  { code: '621000', name: "Počítačové programování" },
  { code: '622000', name: "Poradenství v oblasti počítačů a správa počítačových systémů" },
  { code: '629000', name: "Ostatní činnosti v oblasti informačních technologií a počítačů" },
  { code: '630000', name: "Poskytování počítačové infrastruktury, zpracování dat, hosting a ostatní informační činnosti" },
  { code: '631000', name: "Poskytování počítačové infrastruktury, zpracování dat, hosting a související činnosti" },
  { code: '639000', name: "Činnosti webových vyhledávacích portálů a ostatní informační činnosti" },
  { code: '639100', name: "Činnosti webových vyhledávacích portálů" },
  { code: '639200', name: "Ostatní informační činnosti" },
  { code: '640000', name: "Finanční činnosti, kromě pojišťování a penzijního financování" },
  { code: '641000', name: "Peněžní zprostředkování" },
  { code: '641100', name: "Centrální bankovnictví" },
  { code: '641900', name: "Ostatní peněžní zprostředkování" },
  { code: '642000', name: "Činnosti holdingových společností a účelových finančních společností" },
  { code: '642100', name: "Činnosti holdingových společností" },
  { code: '642200', name: "Činnosti účelových finančních společností" },
  { code: '643000', name: "Činnosti svěřenských a jiných fondů a podobných finančních entit" },
  { code: '643100', name: "Činnosti investičních fondů peněžního trhu a investičních fondů jiných než peněžního trhu" },
  { code: '643200', name: "Činnosti svěřenských fondů, majetkových a agenturních účtů" },
  { code: '649000', name: "Ostatní finanční činnosti, kromě pojišťování a penzijního financování" },
  { code: '649100', name: "Finanční leasing" },
  { code: '649200', name: "Ostatní poskytování úvěrů" },
  { code: '649900', name: "Ostatní finanční činnosti, kromě pojišťování a penzijního financování j. n." },
  { code: '650000', name: "Pojišťovací a zajišťovací činnosti, penzijní financování, kromě povinného sociálního zabezpečení" },
  { code: '651000', name: "Pojišťovací činnosti" },
  { code: '651100', name: "Činnosti v oblasti životního pojištění" },
  { code: '651200', name: "Činnosti v oblasti neživotního pojištění" },
  { code: '652000', name: "Zajišťovací činnosti" },
  { code: '653000', name: "Penzijní financování" },
  { code: '660000', name: "Pomocné činnosti k finančním a pojišťovacím činnostem" },
  { code: '661000', name: "Pomocné činnosti k finančním činnostem, kromě pojišťování a penzijního financování" },
  { code: '661100', name: "Řízení a správa finančních trhů" },
  { code: '661200', name: "Obchodování s cennými papíry a komoditami na burzách" },
  { code: '661900', name: "Ostatní pomocné činnosti k finančním činnostem, kromě pojišťování a penzijního financování" },
  { code: '662000', name: "Pomocné činnosti k pojišťování a penzijnímu financování" },
  { code: '662100', name: "Vyhodnocování rizik a škod" },
  { code: '662200', name: "Činnosti pojišťovacích makléřů a agentů" },
  { code: '662900', name: "Pomocné činnosti k pojišťování a penzijnímu financování j. n." },
  { code: '663000', name: "Správa fondů" },
  { code: '680000', name: "Činnosti v oblasti nemovitostí" },
  { code: '681000', name: "Činnosti v oblasti vlastních nemovitostí a developerské činnosti" },
  { code: '681100', name: "Nákup a následný prodej vlastních nemovitostí" },
  { code: '681200', name: "Developerské činnosti" },
  { code: '682000', name: "Pronájem a správa vlastních nebo pronajatých nemovitostí" },
  { code: '683000', name: "Činnosti v oblasti nemovitostí na základě smlouvy nebo dohody" },
  { code: '683100', name: "Zprostředkování v oblasti nemovitostí" },
  { code: '683200', name: "Ostatní činnosti v oblasti nemovitostí na základě smlouvy nebo dohody" },
  { code: '690000', name: "Právní a účetnické činnosti" },
  { code: '691000', name: "Právní činnosti" },
  { code: '692000', name: "Účetnické a auditorské činnosti; daňové poradenství" },
  { code: '700000', name: "Činnosti řízení podniků a poradenství v oblasti podnikání" },
  { code: '701000', name: "Činnosti řízení podniků" },
  { code: '702000', name: "Poradenství v oblasti podnikání a řízení podniků" },
  { code: '710000', name: "Architektonické a inženýrské činnosti; technické zkoušky a analýzy" },
  { code: '711000', name: "Architektonické a inženýrské činnosti a související technické poradenství" },
  { code: '711100', name: "Architektonické činnosti" },
  { code: '711200', name: "Inženýrské činnosti a související technické poradenství" },
  { code: '712000', name: "Technické zkoušky a analýzy" },
  { code: '720000', name: "Výzkum a vývoj" },
  { code: '721000', name: "Výzkum a vývoj v oblasti přírodních a technických věd" },
  { code: '722000', name: "Výzkum a vývoj v oblasti společenských a humanitních věd" },
  { code: '730000', name: "Činnosti v oblasti reklamy, průzkumu trhu a vztahů s veřejností" },
  { code: '731000', name: "Reklamní činnosti" },
  { code: '731100', name: "Činnosti reklamních agentur" },
  { code: '731200', name: "Zastupování médií při prodeji reklamního času a prostoru" },
  { code: '732000', name: "Průzkum trhu a veřejného mínění" },
  { code: '733000', name: "Činnosti v oblasti vztahů s veřejností a komunikace" },
  { code: '740000', name: "Ostatní odborné, vědecké a technické činnosti" },
  { code: '741000', name: "Specializované návrhářské činnosti" },
  { code: '741100', name: "Činnosti v oblasti průmyslového a módního designu" },
  { code: '741200', name: "Činnosti v oblasti grafického designu a vizuální komunikace" },
  { code: '741300', name: "Navrhování interiérů" },
  { code: '741400', name: "Ostatní specializované návrhářské činnosti" },
  { code: '742000', name: "Fotografické činnosti" },
  { code: '743000', name: "Překladatelské a tlumočnické činnosti" },
  { code: '749000', name: "Ostatní odborné, vědecké a technické činnosti j. n." },
  { code: '749100', name: "Činnosti v oblasti zprostředkování a marketingu patentů" },
  { code: '749900', name: "Všechny ostatní odborné, vědecké a technické činnosti j. n." },
  { code: '750000', name: "Veterinární činnosti" },
  { code: '770000', name: "Činnosti v oblasti pronájmu a leasingu" },
  { code: '771000', name: "Pronájem a leasing motorových vozidel" },
  { code: '771100', name: "Pronájem a leasing osobních automobilů a lehkých motorových vozidel" },
  { code: '771200', name: "Pronájem a leasing nákladních automobilů" },
  { code: '772000', name: "Pronájem a leasing výrobků pro osobní potřebu a převážně pro domácnost" },
  { code: '772100', name: "Pronájem a leasing rekreačních a sportovních potřeb" },
  { code: '772200', name: "Pronájem a leasing ostatních výrobků pro osobní potřebu a převážně pro domácnost" },
  { code: '773000', name: "Pronájem a leasing ostatních strojů, zařízení a hmotných statků" },
  { code: '773100', name: "Pronájem a leasing zemědělských strojů a zařízení" },
  { code: '773200', name: "Pronájem a leasing stavebních strojů a zařízení" },
  { code: '773300', name: "Pronájem a leasing kancelářských strojů a zařízení, včetně počítačů" },
  { code: '773400', name: "Pronájem a leasing vodních dopravních prostředků" },
  { code: '773500', name: "Pronájem a leasing leteckých dopravních prostředků" },
  { code: '773900', name: "Pronájem a leasing ostatních strojů, zařízení a hmotných statků j. n." },
  { code: '774000', name: "Leasing duševního vlastnictví a podobných produktů, kromě děl chráněných autorským právem" },
  { code: '775000', name: "Zprostředkování v oblasti pronájmu a leasingu hmotných statků a nefinančních nehmotných aktiv" },
  { code: '775100', name: "Zprostředkování v oblasti pronájmu a leasingu automobilů, obytných automobilů a přívěsů" },
  { code: '775200', name: "Zprostředkování v oblasti pronájmu a leasingu jiných hmotných statků a nefinančních nehmotných aktiv" },
  { code: '780000', name: "Činnosti související se zaměstnáním" },
  { code: '781000', name: "Činnosti agentur zprostředkujících zaměstnání" },
  { code: '782000', name: "Činnosti agentur zprostředkujících práci na přechodnou dobu a ostatní poskytování lidských zdrojů" },
  { code: '790000', name: "Činnosti cestovních agentur, kanceláří a ostatní rezervační a související činnosti" },
  { code: '791000', name: "Činnosti cestovních agentur a cestovních kanceláří" },
  { code: '791100', name: "Činnosti cestovních agentur" },
  { code: '791200', name: "Činnosti cestovních kanceláří" },
  { code: '799000', name: "Ostatní rezervační a související činnosti" },
  { code: '800000', name: "Pátrací a bezpečnostní činnosti" },
  { code: '800100', name: "Pátrací činnosti a činnosti soukromých bezpečnostních agentur" },
  { code: '800900', name: "Bezpečnostní činnosti j. n." },
  { code: '810000', name: "Činnosti související se stavbami a úpravou krajiny" },
  { code: '811000', name: "Kombinované podpůrné činnosti" },
  { code: '812000', name: "Úklidové činnosti" },
  { code: '812100', name: "Všeobecný úklid budov" },
  { code: '812200', name: "Specializované čištění a úklid budov a průmyslových zařízení" },
  { code: '812300', name: "Ostatní úklidové činnosti" },
  { code: '813000', name: "Činnosti související s úpravou krajiny" },
  { code: '820000', name: "Administrativní, kancelářské a jiné podpůrné činnosti pro podnikání" },
  { code: '821000', name: "Administrativní a kancelářské činnosti" },
  { code: '822000', name: "Činnosti call center" },
  { code: '823000', name: "Pořádání kongresů a veletrhů" },
  { code: '824000', name: "Zprostředkování v oblasti podpůrných činností pro podnikání j. n." },
  { code: '829000', name: "Podpůrné činnosti pro podnikání j. n." },
  { code: '829100', name: "Inkasní činnosti, ověřování solventnosti zákazníka" },
  { code: '829200', name: "Balicí činnosti" },
  { code: '829900', name: "Ostatní podpůrné činnosti pro podnikání j. n." },
  { code: '840000', name: "Činnosti v oblasti veřejné správy, obrany a povinného sociálního zabezpečení" },
  { code: '841000', name: "Činnosti v oblasti veřejné správy a hospodářské, sociální a environmentální politiky" },
  { code: '841100', name: "Všeobecné činnosti veřejné správy" },
  { code: '841200', name: "Regulace činností souvisejících s poskytováním zdravotní péče, vzděláváním, kulturou a jiných služeb pro společnost" },
  { code: '841300', name: "Regulace a podpora podnikatelského prostředí" },
  { code: '842000', name: "Činnosti pro společnost jako celek" },
  { code: '842100', name: "Činnosti v oblasti zahraničních věcí" },
  { code: '842200', name: "Činnosti v oblasti obrany" },
  { code: '842300', name: "Činnosti v oblasti spravedlnosti a soudnictví" },
  { code: '842400', name: "Činnosti v oblasti veřejného pořádku a bezpečnosti" },
  { code: '842500', name: "Činnosti v oblasti požární ochrany" },
  { code: '843000', name: "Činnosti v oblasti povinného sociální zabezpečení" },
  { code: '850000', name: "Vzdělávání" },
  { code: '851000', name: "Preprimární vzdělávání" },
  { code: '852000', name: "Primární vzdělávání" },
  { code: '853000', name: "Sekundární a postsekundární neterciární vzdělávání" },
  { code: '853100', name: "Sekundární všeobecné vzdělávání" },
  { code: '853200', name: "Sekundární odborné vzdělávání" },
  { code: '853300', name: "Postsekundární neterciární vzdělávání" },
  { code: '854000', name: "Terciární vzdělávání" },
  { code: '855000', name: "Ostatní vzdělávání" },
  { code: '855100', name: "Sportovní a rekreační vzdělávání" },
  { code: '855200', name: "Umělecké vzdělávání" },
  { code: '855300', name: "Činnosti autoškol" },
  { code: '855900', name: "Ostatní vzdělávání j. n." },
  { code: '856000', name: "Podpůrné činnosti v oblasti vzdělávání" },
  { code: '856100', name: "Zprostředkování v oblasti vzdělávání" },
  { code: '856900', name: "Podpůrné činnosti v oblasti vzdělávání j. n." },
  { code: '860000', name: "Zdravotní péče" },
  { code: '861000', name: "Lůžková zdravotní péče" },
  { code: '862000', name: "Ambulantní a zubní zdravotní péče" },
  { code: '862100', name: "Všeobecná ambulantní zdravotní péče" },
  { code: '862200', name: "Specializovaná ambulantní zdravotní péče" },
  { code: '862300', name: "Zubní péče" },
  { code: '869000', name: "Ostatní činnosti související se zdravotní péčí" },
  { code: '869100', name: "Činnosti související s diagnostickým zobrazováním a zdravotnické laboratorní činnosti" },
  { code: '869200', name: "Přeprava pacientů vozidly zdravotnické dopravní služby" },
  { code: '869300', name: "Činnosti psychologů a psychoterapeutů, kromě lékařů" },
  { code: '869400', name: "Ošetřovatelské činnosti a činnosti porodních asistentek" },
  { code: '869500', name: "Činnosti fyzioterapeutů" },
  { code: '869600', name: "Činnosti v oblasti tradiční, doplňkové a alternativní medicíny" },
  { code: '869700', name: "Zprostředkování v oblasti zdravotní péče" },
  { code: '869900', name: "Ostatní činnosti související se zdravotní péčí j. n." },
  { code: '870000', name: "Pobytové služby sociální péče" },
  { code: '871000', name: "Pobytové služby sociální péče ve zdravotnických zařízeních lůžkové péče" },
  { code: '872000', name: "Pobytové služby sociální péče pro osoby s duševním onemocněním, mentálním postižením nebo osoby závislé na návykových látkách" },
  { code: '873000', name: "Pobytové služby sociální péče pro seniory nebo osoby s fyzickým nebo smyslovým postižením" },
  { code: '879000', name: "Ostatní pobytové služby sociální péče" },
  { code: '879100', name: "Zprostředkování v oblasti pobytových služeb sociální péče" },
  { code: '879900', name: "Ostatní pobytové služby sociální péče j. n." },
  { code: '880000', name: "Ambulantní nebo terénní sociální služby" },
  { code: '881000', name: "Ambulantní nebo terénní sociální služby pro seniory nebo osoby se zdravotním postižením" },
  { code: '889000', name: "Ostatní ambulantní nebo terénní sociální služby" },
  { code: '889100', name: "Služby pro děti" },
  { code: '889900', name: "Ostatní ambulantní nebo terénní sociální služby j. n." },
  { code: '900000', name: "Umělecká tvorba a činnosti v oblasti scénických umění" },
  { code: '901000', name: "Umělecká tvorba" },
  { code: '901100', name: "Literární a hudební tvorba" },
  { code: '901200', name: "Výtvarná tvorba" },
  { code: '901300', name: "Ostatní umělecká tvorba" },
  { code: '902000', name: "Činnosti v oblasti scénických umění" },
  { code: '903000', name: "Podpůrné činnosti pro uměleckou tvorbu a scénická umění" },
  { code: '903100', name: "Provozování kulturních zařízení a areálů" },
  { code: '903900', name: "Ostatní podpůrné činnosti pro uměleckou tvorbu a scénická umění" },
  { code: '910000', name: "Činnosti knihoven, archivů, muzeí a jiných kulturních zařízení" },
  { code: '911000', name: "Činnosti knihoven a archivů" },
  { code: '911100', name: "Činnosti knihoven" },
  { code: '911200', name: "Činnosti archivů" },
  { code: '912000', name: "Činnosti muzeí, galerií, provozování historických a kulturních památek" },
  { code: '912100', name: "Činnosti muzeí a galerií" },
  { code: '912200', name: "Provozování historických a kulturních památek" },
  { code: '913000', name: "Konzervování, restaurování a jiné podpůrné činnosti pro kulturní dědictví" },
  { code: '914000', name: "Činnosti botanických a zoologických zahrad, přírodních rezervací a národních parků" },
  { code: '914100', name: "Činnosti botanických a zoologických zahrad" },
  { code: '914200', name: "Činnosti přírodních rezervací a národních parků" },
  { code: '920000', name: "Činnosti heren, kasin a sázkových kanceláří" },
  { code: '930000', name: "Činnosti v oblasti sportu, zábavy a rekreace" },
  { code: '931000', name: "Činnosti v oblasti sportu" },
  { code: '931100', name: "Provozování sportovních zařízení" },
  { code: '931200', name: "Činnosti sportovních klubů" },
  { code: '931300', name: "Činnosti fitcenter" },
  { code: '931900', name: "Činnosti v oblasti sportu j. n." },
  { code: '932000', name: "Činnosti v oblasti zábavy a rekreace" },
  { code: '932100', name: "Činnosti zábavních parků" },
  { code: '932900', name: "Činnosti v oblasti zábavy a rekreace j. n." },
  { code: '940000', name: "Činnosti organizací sdružujících osoby za účelem prosazování společných a veřejných zájmů" },
  { code: '941000', name: "Činnosti podnikatelských, zaměstnavatelských a profesních organizací" },
  { code: '941100', name: "Činnosti podnikatelských a zaměstnavatelských organizací" },
  { code: '941200', name: "Činnosti profesních organizací" },
  { code: '942000', name: "Činnosti odborových svazů" },
  { code: '949000', name: "Činnosti ostatních organizací sdružujících osoby za účelem prosazování společných a veřejných zájmů" },
  { code: '949100', name: "Činnosti náboženských organizací" },
  { code: '949200', name: "Činnosti politických organizací" },
  { code: '949900', name: "Činnosti ostatních organizací sdružujících osoby za účelem prosazování společných a veřejných zájmů j. n." },
  { code: '950000', name: "Opravy a údržba počítačů, výrobků pro osobní potřebu a převážně pro domácnost a motorových vozidel a motocyklů" },
  { code: '951000', name: "Opravy a údržba počítačů a komunikačních zařízení" },
  { code: '952000', name: "Opravy a údržba výrobků pro osobní potřebu a převážně pro domácnost" },
  { code: '952100', name: "Opravy a údržba spotřební elektroniky" },
  { code: '952200', name: "Opravy a údržba přístrojů a zařízení převážně pro domácnost, dům a zahradu" },
  { code: '952300', name: "Opravy a údržba obuvi a kožených výrobků" },
  { code: '952400', name: "Opravy a údržba nábytku a bytového zařízení" },
  { code: '952500', name: "Opravy a údržba hodin, hodinek a klenotů" },
  { code: '952900', name: "Opravy a údržba výrobků pro osobní potřebu a převážně pro domácnost j. n." },
  { code: '953000', name: "Opravy a údržba motorových vozidel a motocyklů" },
  { code: '953100', name: "Opravy a údržba motorových vozidel" },
  { code: '953200', name: "Opravy a údržba motocyklů" },
  { code: '954000', name: "Zprostředkování v oblasti oprav a údržby počítačů, výrobků pro osobní potřebu a převážně pro domácnost a motorových vozidel a motocyklů" },
  { code: '960000', name: "Poskytování osobních služeb" },
  { code: '961000', name: "Praní a čištění textilních a kožešinových výrobků" },
  { code: '962000', name: "Kadeřnické a kosmetické činnosti, činnosti denních lázní a podobné činnosti" },
  { code: '962100', name: "Kadeřnické a holičské činnosti" },
  { code: '962200', name: "Kosmetické a podobné činnosti" },
  { code: '962300', name: "Činnosti denních lázní, saun a parních lázní" },
  { code: '963000', name: "Pohřební a související činnosti" },
  { code: '964000', name: "Zprostředkování v oblasti osobních služeb" },
  { code: '969000', name: "Poskytování ostatních osobních služeb" },
  { code: '969100', name: "Poskytování osobních služeb v domácnostech" },
  { code: '969900', name: "Poskytování ostatních osobních služeb j. n." },
  { code: '970000', name: "Činnosti domácností jako zaměstnavatelů domácího personálu" },
  { code: '980000', name: "Činnosti domácností produkujících blíže neurčené výrobky a služby pro vlastní potřebu" },
  { code: '981000', name: "Činnosti domácností produkujících blíže neurčené výrobky pro vlastní potřebu" },
  { code: '982000', name: "Činnosti domácností poskytujících blíže neurčené služby pro vlastní potřebu" },
  { code: '990000', name: "Činnosti exteritoriálních organizací a institucí" },
]
