// Číselník pracovišť finančních úřadů (PRACUFO) — zdroj: adisspr.mfcr.cz
export interface PracufoEntry { code: string; ufo: string; name: string }

export const PRACUFO_CODES: PracufoEntry[] = [
  { code: '2001', ufo: '451', name: "Územní pracoviště pro Prahu 1" },
  { code: '2002', ufo: '451', name: "Územní pracoviště pro Prahu 2" },
  { code: '2003', ufo: '451', name: "Územní pracoviště pro Prahu 3" },
  { code: '2004', ufo: '451', name: "Územní pracoviště pro Prahu 4" },
  { code: '2005', ufo: '451', name: "Územní pracoviště pro Prahu 5" },
  { code: '2006', ufo: '451', name: "Územní pracoviště pro Prahu 6" },
  { code: '2007', ufo: '451', name: "Územní pracoviště pro Prahu 7" },
  { code: '2008', ufo: '451', name: "Územní pracoviště pro Prahu 8" },
  { code: '2009', ufo: '451', name: "Územní pracoviště pro Prahu 9" },
  { code: '2010', ufo: '451', name: "Územní pracoviště pro Prahu 10" },
  { code: '2011', ufo: '451', name: "Územní pracoviště pro Prahu - Jižní Město" },
  { code: '2012', ufo: '451', name: "Územní pracoviště v Praze - Modřanech" },
  { code: '2101', ufo: '452', name: "Územní pracoviště Praha-východ" },
  { code: '2102', ufo: '452', name: "Územní pracoviště Praha-západ" },
  { code: '2103', ufo: '452', name: "Územní pracoviště v Benešově" },
  { code: '2104', ufo: '452', name: "Územní pracoviště v Berouně" },
  { code: '2105', ufo: '452', name: "Územní pracoviště v Brandýse n.L.-Staré Bol." },
  { code: '2106', ufo: '452', name: "Územní pracoviště v Čáslavi" },
  { code: '2109', ufo: '452', name: "Územní pracoviště v Hořovicích" },
  { code: '2110', ufo: '452', name: "Územní pracoviště v Kladně" },
  { code: '2111', ufo: '452', name: "Územní pracoviště v Kolíně" },
  { code: '2112', ufo: '452', name: "Územní pracoviště v Kralupech nad Vltavou" },
  { code: '2113', ufo: '452', name: "Územní pracoviště v Kutné Hoře" },
  { code: '2114', ufo: '452', name: "Územní pracoviště v Mělníce" },
  { code: '2115', ufo: '452', name: "Územní pracoviště v Mladé Boleslavi" },
  { code: '2118', ufo: '452', name: "Územní pracoviště v Nymburku" },
  { code: '2119', ufo: '452', name: "Územní pracoviště v Poděbradech" },
  { code: '2120', ufo: '452', name: "Územní pracoviště v Příbrami" },
  { code: '2121', ufo: '452', name: "Územní pracoviště v Rakovníku" },
  { code: '2122', ufo: '452', name: "Územní pracoviště v Říčanech" },
  { code: '2124', ufo: '452', name: "Územní pracoviště ve Slaném" },
  { code: '2125', ufo: '452', name: "Územní pracoviště ve Vlašimi" },
  { code: '2201', ufo: '453', name: "Územní pracoviště v Českých Budějovicích" },
  { code: '2203', ufo: '453', name: "Územní pracoviště v Českém Krumlově" },
  { code: '2205', ufo: '453', name: "Územní pracoviště v Jindřichově Hradci" },
  { code: '2208', ufo: '453', name: "Územní pracoviště v Písku" },
  { code: '2209', ufo: '453', name: "Územní pracoviště v Prachaticích" },
  { code: '2211', ufo: '453', name: "Územní pracoviště ve Strakonicích" },
  { code: '2212', ufo: '453', name: "Územní pracoviště v Táboře" },
  { code: '2301', ufo: '454', name: "Územní pracoviště v Plzni" },
  { code: '2302', ufo: '454', name: "Územní pracoviště Plzeň-sever" },
  { code: '2303', ufo: '454', name: "Územní pracoviště Plzeň-jih" },
  { code: '2305', ufo: '454', name: "Územní pracoviště v Domažlicích" },
  { code: '2308', ufo: '454', name: "Územní pracoviště v Klatovech" },
  { code: '2312', ufo: '454', name: "Územní pracoviště v Rokycanech" },
  { code: '2313', ufo: '454', name: "Územní pracoviště v Tachově" },
  { code: '2401', ufo: '455', name: "Územní pracoviště v Karlových Varech" },
  { code: '2403', ufo: '455', name: "Územní pracoviště v Chebu" },
  { code: '2407', ufo: '455', name: "Územní pracoviště v Sokolově" },
  { code: '2501', ufo: '456', name: "Územní pracoviště v Ústí nad Labem" },
  { code: '2503', ufo: '456', name: "Územní pracoviště v Děčíně" },
  { code: '2504', ufo: '456', name: "Územní pracoviště v Chomutově" },
  { code: '2505', ufo: '456', name: "Územní pracoviště v Kadani" },
  { code: '2507', ufo: '456', name: "Územní pracoviště v Litoměřicích" },
  { code: '2509', ufo: '456', name: "Územní pracoviště v Lounech" },
  { code: '2510', ufo: '456', name: "Územní pracoviště v Mostě" },
  { code: '2512', ufo: '456', name: "Územní pracoviště v Roudnici nad Labem" },
  { code: '2513', ufo: '456', name: "Územní pracoviště v Rumburku" },
  { code: '2514', ufo: '456', name: "Územní pracoviště v Teplicích" },
  { code: '2515', ufo: '456', name: "Územní pracoviště v Žatci" },
  { code: '2601', ufo: '457', name: "Územní pracoviště v Liberci" },
  { code: '2602', ufo: '457', name: "Územní pracoviště v České Lípě" },
  { code: '2604', ufo: '457', name: "Územní pracoviště v Jablonci nad Nisou" },
  { code: '2607', ufo: '457', name: "Územní pracoviště v Semilech" },
  { code: '2609', ufo: '457', name: "Územní pracoviště v Turnově" },
  { code: '2701', ufo: '458', name: "Územní pracoviště v Hradci Králové" },
  { code: '2707', ufo: '458', name: "Územní pracoviště v Jičíně" },
  { code: '2709', ufo: '458', name: "Územní pracoviště v Náchodě" },
  { code: '2712', ufo: '458', name: "Územní pracoviště v Rychnově nad Kněžnou" },
  { code: '2713', ufo: '458', name: "Územní pracoviště v Trutnově" },
  { code: '2801', ufo: '459', name: "Územní pracoviště v Pardubicích" },
  { code: '2804', ufo: '459', name: "Územní pracoviště v Chrudimi" },
  { code: '2808', ufo: '459', name: "Územní pracoviště ve Svitavách" },
  { code: '2809', ufo: '459', name: "Územní pracoviště v Ústí nad Orlicí" },
  { code: '2810', ufo: '459', name: "Územní pracoviště ve Vysokém Mýtě" },
  { code: '2811', ufo: '459', name: "Územní pracoviště v Žamberku" },
  { code: '2901', ufo: '460', name: "Územní pracoviště v Jihlavě" },
  { code: '2903', ufo: '460', name: "Územní pracoviště v Havlíčkově Brodě" },
  { code: '2910', ufo: '460', name: "Územní pracoviště v Pelhřimově" },
  { code: '2912', ufo: '460', name: "Územní pracoviště v Třebíči" },
  { code: '2913', ufo: '460', name: "Územní pracoviště ve Velkém Meziříčí" },
  { code: '2914', ufo: '460', name: "Územní pracoviště ve Žďáru nad Sázavou" },
  { code: '3001', ufo: '461', name: "Územní pracoviště Brno I" },
  { code: '3002', ufo: '461', name: "Územní pracoviště Brno II" },
  { code: '3003', ufo: '461', name: "Územní pracoviště Brno III" },
  { code: '3004', ufo: '461', name: "Územní pracoviště Brno IV" },
  { code: '3005', ufo: '461', name: "Územní pracoviště Brno-venkov" },
  { code: '3006', ufo: '461', name: "Územní pracoviště v Blansku" },
  { code: '3007', ufo: '461', name: "Územní pracoviště v Boskovicích" },
  { code: '3008', ufo: '461', name: "Územní pracoviště v Břeclavi" },
  { code: '3010', ufo: '461', name: "Územní pracoviště v Hodoníně" },
  { code: '3011', ufo: '461', name: "Územní pracoviště v Hustopečích" },
  { code: '3013', ufo: '461', name: "Územní pracoviště v Kyjově" },
  { code: '3018', ufo: '461', name: "Územní pracoviště ve Veselí nad Moravou" },
  { code: '3019', ufo: '461', name: "Územní pracoviště ve Vyškově" },
  { code: '3020', ufo: '461', name: "Územní pracoviště ve Znojmě" },
  { code: '3101', ufo: '462', name: "Územní pracoviště v Olomouci" },
  { code: '3102', ufo: '462', name: "Územní pracoviště v Hranicích" },
  { code: '3103', ufo: '462', name: "Územní pracoviště v Jeseníku" },
  { code: '3106', ufo: '462', name: "Územní pracoviště v Prostějově" },
  { code: '3107', ufo: '462', name: "Územní pracoviště v Přerově" },
  { code: '3108', ufo: '462', name: "Územní pracoviště ve Šternberku" },
  { code: '3109', ufo: '462', name: "Územní pracoviště v Šumperku" },
  { code: '3110', ufo: '462', name: "Územní pracoviště v Zábřehu" },
  { code: '3201', ufo: '463', name: "Územní pracoviště Ostrava I" },
  { code: '3202', ufo: '463', name: "Územní pracoviště Ostrava II" },
  { code: '3203', ufo: '463', name: "Územní pracoviště Ostrava III" },
  { code: '3205', ufo: '463', name: "Územní pracoviště v Bruntále" },
  { code: '3207', ufo: '463', name: "Územní pracoviště ve Frýdku-Místku" },
  { code: '3210', ufo: '463', name: "Územní pracoviště v Havířově" },
  { code: '3212', ufo: '463', name: "Územní pracoviště v Karviné" },
  { code: '3213', ufo: '463', name: "Územní pracoviště v Kopřivnici" },
  { code: '3214', ufo: '463', name: "Územní pracoviště v Krnově" },
  { code: '3215', ufo: '463', name: "Územní pracoviště v Novém Jičíně" },
  { code: '3216', ufo: '463', name: "Územní pracoviště v Opavě" },
  { code: '3218', ufo: '463', name: "Územní pracoviště v Třinci" },
  { code: '3301', ufo: '464', name: "Územní pracoviště ve Zlíně" },
  { code: '3304', ufo: '464', name: "Územní pracoviště v Kroměříži" },
  { code: '3306', ufo: '464', name: "Územní pracoviště v Otrokovicích" },
  { code: '3307', ufo: '464', name: "Územní pracoviště v Rožnově pod Radhoštěm" },
  { code: '3308', ufo: '464', name: "Územní pracoviště v Uherském Brodě" },
  { code: '3309', ufo: '464', name: "Územní pracoviště v Uherském Hradišti" },
  { code: '3310', ufo: '464', name: "Územní pracoviště ve Valašském Meziříčí" },
  { code: '3312', ufo: '464', name: "Územní pracoviště ve Vsetíně" },
]
